### ISSUE TITLE
3.1.1 - Volume Page count off by factor of Sector Size

### ISSUE THREAD

**Issue by user31415** [sleuthkit/autopsy#1006]
Autopsy 3.1.1

Select "Data Sources" in top left, and "disk.img" in directory listing right, produces a CORRECT "page count" in the bottom right panel that correctly accounts for the size of the drive.

Select "disk.img" in top left, and "volume" in directory listing right, produces a WRONG "page count" in the bottom right panel that is off by a multiplying factor of 512 (sector size). This prevents accessing 99.8% of the volume in this panel.

**Comment by bcarrier** [comment]
Fixed (and also reported on forum: http://forum.sleuthkit.org/viewtopic.php?f=6&t=490).
