### ISSUE TITLE
scalpel - included (partial?) but apparently nonfunctional & no ref in KNOWN_ISSUES.txt 

### ISSUE THREAD

**Issue by johnmccash** [sleuthkit/autopsy#1010]
I'm guessing, based on the response to issue #403 last March, that the scalpel plugin doesn't really work yet. That being the case, this 'bug' really relates to the lack of documentation in the release regarding this issue. Please update KNOWN_ISSUES.txt, and possibly the integral help. It might be worthwhile, as well, to either remove the plugin until it can actually be used, or else do something to make it obvious to people looking through their plugins that it doesn't work, so they don't waste time on it. On the other hand, if it can be used in some fashion, it would be nice to have some sort of documentation as to how exactly to employ it.
Thanks

**Comment by bcarrier** [comment]
Fair enough.  The next release has a PhotoRec plug-in, so that Scalpel effort is dead for quite a while until some memory leaks can be fixed in it. We should make it invisible to the user though.

**Comment by bcarrier** [comment]
Just removed it from the Autopsy project so that it is not visible to user in plug-ins area. 

Checkin: 57811bb
