### ISSUE TITLE
Track and show what ingest was performed

### ISSUE THREAD

**Issue by adam-m** [sleuthkit/autopsy#110]
It is useful to know what ingest modules were ran on which image and when.

We could keep track of that somehow (XML per case?).

We could display this information in directory tree as a separate node showing history of ingests.

Perhaps some of the ingest nodes underneath could take us user to  their raw results (combining this feature  with ingest output viewing feature).

Handle running ingest on the same data so we do not produce duplicate results.

**Comment by markmckinnon** [comment]
This is now include in Autopsy under Case -> Data Source Summary -> Ingest History
