### ISSUE TITLE
java.lang.UnsatisfiedLinkError when starting from NetBeansIDE

### ISSUE THREAD

**Issue by LoWang123** [sleuthkit/autopsy#1554]
Hi,

I recently cloned the developing version of autopsy 3 because I'm planning to implement two modules in my studies of computer science. I followed the guidelines described in BUILDING.txt and successfully built the project using the NetBeansIDE. When I start the project from NetBeans the splashscreen starts and after the "Turning on Modules" step i recieve this excepton text:

org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: C:\Users\Tobias\Documents\NetBeansProjects\autopsy-develop\build\cluster\modules\org-sleuthkit-autopsy-core.jar: java.lang.UnsatisfiedLinkError: org.sleuthkit.datamodel.SleuthkitJNI.getVersionNat()Ljava/lang/String;

whenever I am trying to activate a module afterwards in tools>plugins>installed I'm getting pretty much the same exception:

Activation failed: StandardModule:org.sleuthkit.autopsy.core jarFile: C:\Users\Tobias\Documents\NetBeansProjects\autopsy-develop\build\cluster\modules\org-sleuthkit-autopsy-core.jar: java.lang.UnsatisfiedLinkError: org.sleuthkit.datamodel.SleuthkitJNI.getVersionNat()Ljava/lang/String;

When I'm using the released version of Autopsy 3 which has been installed using the corresponding binary the application works just fine.

As of now I'm using Windows 10, NetBeansIDE 8.0.2 and jdk1.8.0_51

Thanks for your help and best regards,
Tobias

**Comment by rcordovano** [comment]
The Autopsy source has a dependency on the SleuthKit. This error usually indicates that the SleuthKit native libraries and Java bindings have not been built. This is described in BUILDING.txt thus:

2) Get Sleuth Kit Setup
2a) Download and build a Release version of Sleuth Kit (TSK) 4.0. See
    win32\BUILDING.txt in the TSK package for more information. You need to 
    build the tsk_jni project. Select the Release_PostgreSQL Win32 or x64 target,
    depending upon your target build. You can use a released version or download 
    the latest from github:
- git://github.com/sleuthkit/sleuthkit.git

2b) Build the TSK JAR file by typing 'ant dist-PostgreSQL' in
    bindings/java in the
    TSK source code folder from a command line. Note it is case
    sensitive. You can also add the code to a NetBeans project and build
    it from there, selecting the dist-PostgreSQL target.

2c) Set TSK_HOME environment variable to the root directory of TSK

The SleuthKit has its own dependencies; see BUILDING.txt for TSK for details.

**Comment by rcordovano** [comment]
I apologize for the delayed response above - I see that this issue was posted in September 2015! Making another pass through the issues, it seems reasonable to consider this issue to be stale. LoWang123, please feel free to submit again if you still are having problems building Autopsy from source. Thanks!
