### ISSUE TITLE
Select folder for Ingest : request for feature

### ISSUE THREAD

**Issue by pmourre** [sleuthkit/autopsy#193]
Hi again, 

In the Ingest module il would be great to be able to select (begining or pattern of  path)  folder which can be included or excluded by the ingest processs. 

Thanks,

**Comment by rcordovano** [comment]
The feature requested is not clearly understood, and three years have elapsed without a reply to the request for clarification. We will close this issue at this time'; pmourre, please feel to submit a more detailed request, thanks!
