### ISSUE TITLE
Related to image in HTML report

### ISSUE THREAD

**Issue by ruchambapat** [sleuthkit/autopsy#1993]
when you open your report in HTML format, you get a image information. This is really confusing, about what image it is providing a description. I am first time user of Autopsy.

**Comment by rcordovano** [comment]
The Case Summary page of the HTML report provides a few details about the forensic images that have been added to the case. These images are analyzed by the SleuthKit to populate the case database with metadata about their volumes, file systems, files, etc. The images are usually also analyzed by the plugin ingest modules you have installed, many of which come with Autopsy "out of the box". 

In truth, the use of the phrase "Image Information" in the report is a bit too narrow.  Autopsy can also ingest and analyze logical/local files and local disks (e.g., a thumb drive); the upcoming Autopsy 4.1.0 release will also ingest VMWare virtual machine files and Microsoft Virtual Hard Drive files. So a better term these days, one that is slowly being integrated throughout Autopsy, is "data source." A forensic image is one kind of data source, a collection of local/logical files is another kind of data source, and a thumb drive is yet another type of data source. This part of the report would probably be better titled "Data Source Information."

And of course, "image" is an overloaded term. We call all sorts of media files "images", for example. 

So what is it that is confusing about this part of the report? Please provide more specifics. Thanks!

Richard Cordovano
Autopsy Team Lead for Basis Technology

**Comment by rcordovano** [comment]
Did my explanation help clear things up? If not, please feel free to resubmit the question with some specifics about what was confusing, thanks!
