### ISSUE TITLE
Spelling mistakes and Grammar mistakes in documentation files

### ISSUE THREAD

**Issue by ruchambapat** [sleuthkit/autopsy#2010]
Following files have Spelling mistakes and Grammar mistakes-
some files are at locaion- autopsy/docs/doxygen-user

autopsy/docs/doxygen-user/stix.dox- Spelling mistakes
autopsy/docs/doxygen-user/tagging.dox- Spelling mistakes
autopsy/docs/doxygen-user/timeline.dox- Spelling mistakes,grammar mistakes
autopsy/docs/doxygen-user/filetype.dox- Spelling mistakes
autopsy/docs/doxygen-user/ingest.dox- spelling mistakes
autopsy/docs/doxygen-user/image_gallery.dox- spelling mistakes

Some files are at locaion- autopsy/docs/doxygen
autopsy/docs/doxygen/modResult.dox- spelling mistakes
autopsy/docs/doxygen/regressionTesting.dox- spelling mistakes
autopsy/docs/doxygen/workflow.dox- spelling mistakes
autopsy/docs/doxygen/platformConcepts.dox- spelling mistakes

**Comment by ruchambapat** [comment]
Corrected the spelling mistakes and grammar mistakes in files listed in above comment and pull request is sent-
#2011

**Comment by rcordovano** [comment]
The pull request with the corrections has been implemented. Closing this issue.
