### ISSUE TITLE
Log Extract file is 0 length

### ISSUE THREAD

**Issue by ritabarr** [sleuthkit/autopsy#2021]
Hello, 
I'm working to extract the remote session log from a Win7 (evtx) image created with FTK.  I see the file in Autopsy and it has a file length that appears to be pretty large however when I extract it is 0 length and it cannot be opened by the windows event viewer.  I've extracted other files (video, excel, etc.) w/o issue.

Is this an issue with Autopsy or am I not doing something correctly? -- the documentation isn't directing me to any potential other methods of extraction for log files -- Should I use another command line tool to get this file? 

Thanks!
Rita.

**Comment by rcordovano** [comment]
It does not sounds like you are doing anything wrong. Is the log a deleted file, by any chance? The size you see reported for files comes from the file system metadata for the file and may not reflect the actual file content available.

**Comment by rcordovano** [comment]
Have you made any progress towards resolution, ritabarr?

**Comment by ritabarr** [comment]
Yes, it appears as if the completion message appears before the file is actually ready for viewing.  I just had to wait awhile while the file assembled itself then all was ok.  It was pretty large file so it took at bit.

Rita M. Barrios, Ph.D.
Associate Professor & Dept. Chair
Computer Information Systems and Cyber Security

College of Liberal Arts and Education
University of Detroit Mercy
4001. W. McNichols Rd.
Detroit Mi 48221
O- 313.993.3338
C- 313.443.4782
Email: barriorm@udmercy.edu<mailto:barriorm@udmercy.edu>

[http://community.udmercy.edu/view.image?Id=1086]

**Comment by rcordovano** [comment]
Thanks, Rita, I'm glad to hear that everything is o.k. I will close out this issue.
