### ISSUE TITLE
File Signature Module

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/autopsy#203]
We need an ingest module to detect file types based on signature. It would post the file type to the blackboard using the TSK_FILE_TYPE_SIG attribute. Ideally, users can update the signatures.

**Comment by sarahbethash** [comment]
Should this feature request be marked as closed? The FileType tab allows you to sort files by type and perform extension and type validation.

**Comment by rcordovano** [comment]
The file type identification module supports the creation of user-defined types that supplement or override standard MIME types. The user-defined file types feature currently allows multiple single-signature definitions to be mapped to a given type, and a modification to allow multiple signatures per type definition is pending integration.
