### ISSUE TITLE
File Type / Extension Mismatch

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/autopsy#204]
We should have a module that uses the file type from a module in Issue #203 and detects if its extension does not match the file type.  It should post to the blackboard with a new attribute if this case happens and it should be reported in the UI.

**Comment by sarahash** [comment]
Should this feature request be marked as closed? The FileType tab allows you to sort files by type and perform extension and type validation.

**Comment by rcordovano** [comment]
The file extension mismatch module compares file type to extension and generates an extension mismatch artifact if a mismatch is detected.

The file type identification module supports the creation of user-defined types that supplement or override standard MIME types. The user-defined file types feature currently allows multiple single-signature definitions to be mapped to a given type, and a modification to allow multiple signatures per type definition is pending integration.

The next step will be to use the results of the file type identification module to populate the Views, File Types part of the tree view.
