### ISSUE TITLE
Ingest messages "timestamp" shows time only

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#2060]
The "Ingest messages" window that shows various info and error messages from the modules has a "Timestamp" column. This column only shows the time, there's no date shown.

**Comment by rcordovano** [comment]
Thanks, I have added this issue to our internal bug tracking system.

**Comment by michaelctaylor** [comment]
Has there been any traction with this?  I has been four years and I am not seeing a date stamp on the Ingest Messages window.  A bit of snag for when needing to properly track and report on findings and issues with a forensic case. Version 4.15.0
Great product however.

**Comment by rcordovano** [comment]
@praemunio, this issue has languished. It seems like it should be a quick and easy fix. I will try to allocate some resources to it for the next release.

**Comment by ethteck** [comment]
I'm happy to share that this issue will be fixed in the upcoming 4.16.0 release. #5958

**Comment by praemunio** [comment]
Outstanding and thank you for the immediate attention on this.

**Comment by rcordovano** [comment]
I am going to close this story; as @ethteck says, the data and time will be displayed in the upcoming release.
