### ISSUE TITLE
InterestingFiles Module needed

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/autopsy#208]
We need a module similar to the InterestingFiles module in the TSK Framework that allows users to specify files with certain extensions or file names and they are flagged in the blackboard with an TSK_INTERESTING_FILE artifact and can then be exported.

**Comment by rcordovano** [comment]
This module now exists. Users can define rules with name, path, extension, MIME type and size conditions. This module is actually more capable than the TSK Framework module.
