### ISSUE TITLE
Module to calculate / verify image hash value

### ISSUE THREAD

**Issue by bcarrier** [sleuthkit/autopsy#209]
User requested that he can calculate hash value of image. It was requested that this be done when adding the image to the case, but that will delay the process.  I'd suggest it be done as an Ingest Module that can calculate and/or verify image hash. 

Thoughts:
- I don't think we currently have a place in the database to store it. 
- We need to figure out how to flag the image in the database if it fails validation.

**Comment by markmckinnon** [comment]
This has been implemented.  Data Source Integrity Ingest module.
