### ISSUE TITLE
Add Releases to Github

### ISSUE THREAD

**Issue by moshekaplan** [sleuthkit/autopsy#2275]
Github supports distributing releases, as described here: https://help.github.com/articles/creating-releases/

Would it be possible to add the download links for released versions of Autopsy to Github?

**Comment by seannicholls** [comment]
I would like to see this as well.

**Comment by bcarrier** [comment]
We started doing this a little while ago.  The latest one is here: https://github.com/sleuthkit/autopsy/releases/tag/autopsy-4.5.0
