### ISSUE TITLE
Autopsy 4.1.1 Python Issue

### ISSUE THREAD

**Issue by jblukach** [sleuthkit/autopsy#2309]
RunExe.py example python module still does not allow the subprocess to execute.  Will this feature still be available for python modules?

https://github.com/sleuthkit/autopsy/tree/develop/pythonExamples/Aug2015DataSourceTutorial

**Comment by bcarrier** [comment]
What are you seeing for an error?  I just ran the runexe.py module in 4.1.1 and didn't get any errors.

**Comment by jblukach** [comment]
Ah, Windows 10, I will write up and post what i found - sorry for the noise
