### ISSUE TITLE
Compile on Mint Sarah

### ISSUE THREAD

**Issue by barnie995** [sleuthkit/autopsy#2313]
Having issues compiling Autopsy on Mint Sarah.  

Autopsy version: 4.1.1

TSK: 4.3.0

Gets to the find the TSK Jars and errors out.  Finds TSK alright tho.   

<spoiler> getTSKJars:

BUILD FAILED
/home/josh/Desktop/Autopsy_and_shits/autopsy/netbeans-plat/8.1/harness/suite.xml:187: The following error occurred while executing this line:
/home/josh/Desktop/Autopsy_and_shits/autopsy/Core/build.xml:31: The following error occurred while executing this line:
/home/josh/Desktop/Autopsy_and_shits/autopsy/Core/build.xml:21: Warning: Could not find file /home/josh/Desktop/Autopsy_and_shits/sleuthkit-4.3.0/tsk/bindings/java/dist/Tsk_DataModel_PostgreSQL.jar to copy.

Total time: 11 seconds

</spoiler>

Is there anything simple I doing that I should be doing or something really strange and abstract?

Cheers

**Comment by hoyt-harness** [comment]
Hello Josh... Find the file "Tsk_DataModel.jar" in the directory listed in the error and rename it manually to "Tsk_DataModel_PostgreSQL.jar", then try a clean build.

**Comment by barnie995** [comment]
There is no /sleuth-kit-4.3.0/tsk/bindings folder

**Comment by barnie995** [comment]
Worked it out.  Copying the bindings folder from here: /home/josh/Desktop/Autopsy_and_shits/sleuthkit-4.3.0/

Into here: /home/josh/Desktop/Autopsy_and_shits/sleuthkit-4.3.0/tsk/  and renaming the .jar file worked.  Thank you
