### ISSUE TITLE
Now 2 use Autopsy with selective imaging

### ISSUE THREAD

**Issue by halbbob** [sleuthkit/autopsy#253]
Hi guys,

I need to use Autopsy for developing a java-based selective imaging model. This is my research project. The developed system needs to:
1. Scans the targeted storage device to find all active and deleted data files.
2. Allows the investigator 2 search for the relevant data using keywords and parameters
3. Images the selected data files into AFF4.

What is/are the best method/steps to achieve the above issue. For example, using modules or modifying Autopsy java classes.

Thanks for your contribution

**Comment by markmckinnon** [comment]
Closing as answered.  Please reopen if you think this was closed in error.
