### ISSUE TITLE
Updating jython

### ISSUE THREAD

**Issue by AlexXandreE** [sleuthkit/autopsy#2930]
Hi everyone, 
I'm trying to make a python module but I got some issues with jython 2.7.0, so I can only use 2.7.1 that released this month or some older version.
But autopsy 4.4 is using 2.7.0, can i switch version on autopsy and if yes how?

Thx, Alexandre F.

**Comment by rcordovano** [comment]
@AlexXandreE, the Python support in Autopsy relies on Jython, which currently supports Python 2.7.0 (http://www.jython.org/downloads.html). So I am sorry to have to tell you that there is currently no way to change the version of Python you can use to make Autopsy modules.

Richard Cordovano
Autopsy Team Lead
Director of Engineering - Digital Forensics, Basis Technology

**Comment by AlexXandreE** [comment]
oh ok, thx anyway i will try to get around then :)
Thx for the quick reply.

**Comment by rcordovano** [comment]
You're welcome.
