### ISSUE TITLE
Autopsy fails to load libtsk_jni in Ubuntu 13.04 x64

### ISSUE THREAD

**Issue by peterclemenko** [sleuthkit/autopsy#311]
Autopsy fails to load libtsk_jni in Ubuntu 13.04 x64 with Oracle JDK 7u40

Log:
https://gist.github.com/th3flyboy/7548cea70c559e46f09e

**Comment by markmckinnon** [comment]
This is being closed based on the version of Autopsy being used.  If this is still an issue please reopen.
