### ISSUE TITLE
Autopsy not building

### ISSUE THREAD

**Issue by jfehrman** [sleuthkit/autopsy#3219]
Autopsy not building on my system after checkout.  Used Open-JDK and the default JDK on Ubuntu.  Using Java 8.  I know most of the users are on Windows, but I primarily work on Linux.  Does anyone have any advice on how to get this running?

> No such dir /home/solver.net/jfehrman/Development/autopsy/CoreLibs/test/unit/src; should not define test deps
> org.sleuthkit.autopsy.corelibs.harness.init:
> org.sleuthkit.autopsy.corelibs.init:
> org.sleuthkit.autopsy.corelibs.up-to-date:
> org.sleuthkit.autopsy.corelibs.compile:
> Created dir: /home/solver.net/jfehrman/Development/autopsy/CoreLibs/build/classes
> Compiling 2 source files to /home/solver.net/jfehrman/Development/autopsy/CoreLibs/build/classes
> warning: Supported source version 'RELEASE_6' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.8'
> warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '1.8'
> warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '1.8'
> /home/solver.net/jfehrman/Development/autopsy/CoreLibs/src/org/sleuthkit/autopsy/corelibs/SigarLoader.java:21: error: package com.sun.javafx does not exist
> import com.sun.javafx.PlatformUtil;
> 1 error
> 3 warnings
> /home/solver.net/jfehrman/Development/autopsy/netbeans-plat/8.2/harness/suite.xml:187: The following error occurred while executing this line:
> /home/solver.net/jfehrman/Development/autopsy/netbeans-plat/8.2/harness/common.xml:225: Compile failed; see the compiler error output for details.
> BUILD FAILED (total time: 1 second)

**Comment by marshalla99** [comment]
I have a fairly ugly script for Debian that pulls in all the dependencies that I've found and gets a working build now. Happy to share if that might help you.

**Comment by jfehrman** [comment]
@marshalla99.  That would be great.  Could you please share the script?

**Comment by marshalla99** [comment]
OK, here it is. It’s not big and definitely not clever, because it’s been hacked together whenever I have a bit of time to spare.

However it pulls in everything needed to get a working 4.5.1 build on an Osboxes.Org VM of Debian.

**Comment by marshalla99** [comment]
Stoopid file extension filter blocked it.

[NewAutopyInst.sh.txt](https://github.com/sleuthkit/autopsy/files/1487915/NewAutopyInst.sh.txt)

**Comment by jfehrman** [comment]
Thanks for posting the file @marshalla99.  What is this file?  https://53efc0a7187d0baa489ee347026b8278fe4020f6.googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/libewf-20140608.tar.gz

**Comment by marshalla99** [comment]
a) not used any more - it's hang over from an older script that I incorporated - and that line is commented out
b) a source archive for libewf that someone thought was needed, but the later git clone pulls it in now.

**Comment by jfehrman** [comment]
@marshalla99 Thanks for the help.  The script didn't work 100% however I was able to supplement by running some commands by hand to get the tool running.  I am not running in Autopsy and I am going to start the process of writing plugins.  I have an idea to use the netbeans docker container to streamline this process.  https://hub.docker.com/r/fgrehm/netbeans/  Could you publish your script on github?  If you don't want to can I?  I'd like to build out a Netbeans image that people can use to quick start development using Netbeans.

**Comment by marshalla99** [comment]
I'd prefer not to publish that script as it's an amalgamation of work done by others. It wouldn't be fair to release it without properly acknowledging their contributions.

It's also quite ugly at the moment and really not fit to be seen.

**Comment by jfehrman** [comment]
Is there any way I can clean up the code and give credit to those other contributors.  Now that I have seen the script I can't unsee it and it is the fastest and best way to set up autopsy.  I also don't want to release it without giving those individuals credit that deserve it, but I will clean it up before it goes out the door.

**Comment by marshalla99** [comment]
Give me a few days to sort it out. I should probably get it inserted into the Linux build ReadMe file somehow.

**Comment by marshalla99** [comment]
OK - I have an updated script with credits, comments and a patch for a current netbeans server problem. 

Since it's a Linux script, can we close this thread and keep the discussion to one of the other Linux package/build threads?

**Comment by jfehrman** [comment]
@marshalla99 Great I will continue the discussion on the other thread.  Thanks again for all your help!
