### ISSUE TITLE
Make package / install candidate for Mac OS X

### ISSUE THREAD

**Issue by seannicholls** [sleuthkit/autopsy#3291]
Similar to #2938 and #2863

I believe much of the work done in getting Autopsy to work for Linux can be used to also get it working satisfactorily on Mac OS X systems. That said, there will doubtless be system specific concerns to overcome, hence the need for this feature request.

I have successfully built Autopsy on Ubuntu 16.04 LTS and will be contributing to efforts to make a more streamlined 'official' means than is presently available. I have yet to be able to produce something which works on a Mac OS X system, however. As such, I think some effort should be put into getting Autopsy working on Mac Operating Systems.

**Comment by marshalla99** [comment]
Given the issues with some of the functionality, even after a "successful" build, I think we have bigger problems than "just" porting to deal with. 

We need to get a relatively stable version which works on both Windows and Linux, and which handles installation of alternative supporting software (e.g. PhotoRec) before we introduce a third platform, IMNSHO.

**Comment by seannicholls** [comment]
@marshalla99 I don't disagree, however I would like to keep this issue open as something to aim for.

I think that once Linux issues are resolved, I think porting to Mac should be "relatively easy" - at least by comparison.

In terms of priority, I would certainly rate it lower than Linux by a wide margin.

**Comment by marshalla99** [comment]
I agree.

Right now - we seem to have some java code which is not particularly portable. If that is fixed for Linux it *might* be OK for Mac as well. That would leave the issue of the external support programs and their installation. Given the *nix nature of Mac, that side of porting would, I hope, be simpler - especially if we can use Macports, fink or Homebrew to assist with those.

**Comment by marshalla99** [comment]
I take back my comment about the java code as it seems it was more of a missing package problem. The Linux build is actually pretty stable and, I think, gives a pretty good indication of the sort of dependencies we may have on Mac.

**Comment by bcarrier** [comment]
Closign this since you can now install on OS X.  Instructions are [here](https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt)
