### ISSUE TITLE
How do I get the file contents using the Sleuthkit's AbstractFile class

### ISSUE THREAD

**Issue by jfehrman** [sleuthkit/autopsy#3343]
According to the [documentation on the Sleuthkit](http://www.sleuthkit.org/sleuthkit/docs/jni-docs/4.3/classorg_1_1sleuthkit_1_1datamodel_1_1_abstract_file.html#affb9fb21f6f25ad6bd864b34ee0f8b3b) there is a function for reading the files contents into a byte array named read.  I am using this in the process function of an Autopsy Python plugin.  I am trying to extract contents from the file and create artifacts with the contents.  The byte array after I call the read function always comes up empty.  I checked the file manually to ensure the file has contents.  I think I am probably doing it wrong but I am going to attach a code snippet so that someone can tell me how I am doing it wrong.

`
    def process(self, file):

        # Skip all non files and any files that aren't a CSV file.
        if (file.isFile() == False or file.getNameExtension() != "csv"):

            log("Skipping " + file.getNameExtension())
            return IngestModule.ProcessResult.OK

        # Get all of the text content from the file.
        fileSize = file.getSize()

        log("Abstract File: " + file.toString())
        byteContent = bytearray(fileSize)

        if (fileSize > 0):

            file.read(byteContent, 0, fileSize)

        for byte in byteContent:

            log("Bytes: " + str(byteContent))

        content = byteContent.decode("utf-8")
        log("Content: " + content)

        # Load all of the records from the file.
        adapter = CsvFileAdapter()
        records = adapter.adapt(content)

        # Create artifacts for the records.
        log("Hello world!")`

**Comment by rcordovano** [comment]
@jfehrman, here is an excerpt form one of our sample Python modules that shows how to read in file content using Python: 

` 
            inputStream = ReadContentInputStream(file)
            buffer = jarray.zeros(1024, "b")
            totLen = 0
            len = inputStream.read(buffer)
            while (len != -1):
                    totLen = totLen + len
                    len = inputStream.read(buffer)`

You can find Autopsy Python module sample code at https://github.com/sleuthkit/autopsy/tree/develop/pythonExamples.

**Comment by markmckinnon** [comment]
Here is my suggestion for you then.

Write the file from autopsy to the temp directory using code like this:

# Sets up file manager to search for a file
fileManager = Case.getCurrentCase().getServices().getFileManager()
# Find the file
files = fileManager.findFiles(dataSource, "Some File")
# Get the number of files found - good for debugging
numFiles = len(files)
# Shows how many files found in log
self.log(Level.INFO, "found " + str(numFiles) + " files for file_name ==> " + "Some File")

# Writes out the file with the inode in front in case of duplicate files                    
for file in files:	
    FileToWrite = os.path.join(Case.getCurrentCase().getTempDirectory(), file.getName() + "-" + str(file.getId()))
    ContentUtils.writeToFile(file, File(FileToWrite))

Then for each file that is written out use this sample code to read in the CSV file and add it as an artifact.  If the file has a header line then it will read that and create the attributes based on that header line, if not you will have to create the header line but that should not be to hard.

       # Setup Artifact
        try:
            self.log(Level.INFO, "Begin Create New Artifacts")
            artID_ls = skCase.addArtifactType( "TSK_CSV_EXAMPLE", "CSV Sample File")
        except:		
            self.log(Level.INFO, "Artifacts Creation Error, some artifacts may not exist now. ==> ")
        artifact_name = "TSK_CSV_EXAMPLE"
        artID_csv = skCase.getArtifactTypeID(artifact_name)
        artID_csv_evt = skCase.getArtifactType(artifact_name)

       # Read CSV File and Import into Autopsy
        for file in files:
            heading_read = False
            attribute_names = []
            with open('D:\\Users\\mmckinnon2\\Downloads\\TechCrunchcontinentalUSA.csv', 'rU') as csvfile:
                csvreader = csv.reader(csvfile, delimiter=',', quotechar='|')
                for row in csvreader:
                    if not heading_read:
                        for col_name in row:
                            attribute_names.append("TSK_CSV_" + col_name.upper())
                            try:
                                attID = skCase.addArtifactAttributeType("TSK_CSV_" + col_name.upper(), BlackboardAttribute.TSK_BLACKBOARD_ATTRIBUTE_VALUE_TYPE.STRING, col_name)
                            except:
                                self.log(Level.INFO, "attribute already Exists. ==> " + "TSK_CSV_" + col_name.upper())
                            self.log(Level.INFO, "attribute_created. ==> " + "TSK_CSV_" + col_name.upper())
                        heading_read = True
                    else:
                        art = file.newArtifact(artID_csv)
                        for (data, head) in zip(row, attribute_names): 
                            art.addAttribute(BlackboardAttribute(skCase.getAttributeType(head), CSVimportIngestModuleFactory.moduleName, data))
                            #self.log(Level.INFO, "artifact_created. ==> " + "TSK_CSV_" + col_name.upper() + " =====> " + data)

**Comment by kefir-** [comment]
Is it possible to get the file slack from the python interface?

Also, it'd be nice if there were a more pythonesque way to read a file by wrapping the ReadContentInputStream / jarray stuff in a file-like object for further use in python. A random example of a tool that accepts file-like objects is "mutagen", which takes an audio file as input and guesses the file type. I'm linking this because it has a good description of what a file-like object is expected to look like:

http://mutagen.readthedocs.io/en/latest/user/filelike.html

**Comment by jfehrman** [comment]
@rcordovano and @markmckinnon Thanks for the suggestions.  Right now I based on the solutions provided I was able to get a bit further down the line.  I appreciate the help getting past the initial hurdle.  I followed Mark's example a bit more closely as I could find more examples like his in the [AutopsyPlugins](https://github.com/markmckinnon/Autopsy-Plugins) repository.
