### ISSUE TITLE
Export carved URLs/keywords

### ISSUE THREAD

**Issue by xeroceph** [sleuthkit/autopsy#3373]
I have a relatively small case with > 300k carved URLs; I'm looking for an easy way to rapidly "dump" these discovered results to some sort of plain text file, CSV, etc. Apologies if something like this is already implemented within the framework - I haven't seen anything documented for it. The Java interface doesn't seem to support multi-selection or copy-paste of these URLs/keyword hits to another document either. From a time-critical event perspective, I think this capability would be a valuable feature request for many incident responders to dump these items quickly and sift through the results.

**Comment by marshalla99** [comment]
Can't that be done by tagging the results (which can be done en-masse) and then using the Report Generator to dump just the tagged entries to an Excel sheet or Tab delimited file?
