### ISSUE TITLE
Autopsy attempting external internet connection

### ISSUE THREAD

**Issue by newmajam** [sleuthkit/autopsy#3447]
We have experienced problems with the Autopsy 4.5.0 GUI hanging immediately on simple operations after startup.
I was able to trace this to a connection being attempted to the external address 'apache2-noxim.canby.dreamhost.com' which was seemingly being blocked by our web proxies.
When the Autopsy proxy settings were changed from 'Use System Proxy Settings' to 'No Proxy' the GUI remained responsive.
I do not know whether the connection to this address was successful, but the deployment of Autopsy will be a challenge for my company if the software is going to be initiating undocumented attempts to access web addresses.

**Comment by marshalla99** [comment]
Is this from the official package or one of the development versions?

**Comment by newmajam** [comment]
Thanks for looking into it! I'll feed this back to our developer.

**Comment by bcarrier** [comment]
It's probably the request to see if there is a new version of the software available.  It comes as part of the NetBeans framework that we use.  It is reaching out to sleuthkit.org, which is hosted at the above provider.
