### ISSUE TITLE
Linux: include an export of the JAVA_HOME environment variable in the docs

### ISSUE THREAD

**Issue by dkarpo** [sleuthkit/autopsy#3561]
Hello.

The current instructions for Autopsy under Linux Requisites reference the Oracle docs for setting JAVA_HOME.  The problem is that the JAVA_HOME variable needs to be set, as well as exported, so that it is available to child processes during unix_setup.sh.  Recommend updating the instructions to include this export.  ie:

```bash
dk@anubis:~/src/autopsy-4.6.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
dk@anubis:~/src/autopsy-4.6.0$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
dk@anubis:~/src/autopsy-4.6.0$ sh unix_setup.sh
/usr/bin/photorec found
ERROR: JAVA_HOME environment variable must be defined
```
With JAVA_HOME set and exported, the unix_setup.sh will run correctly:

```bash
dk@anubis:~/src/autopsy-4.6.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
dk@anubis:~/src/autopsy-4.6.0$ export JAVA_HOME
dk@anubis:~/src/autopsy-4.6.0$ sh unix_setup.sh 
/usr/bin/photorec found
Java found in /usr/lib/jvm/java-8-openjdk-amd64
/usr/share/java/sleuthkit-4.6.0.jar found
Copying into the Autopsy directory
Autopsy is now configured. You can execute bin/autopsy to start it
```

**Comment by nannib** [comment]
or simply log-out and log-in and the variable is exported automatically (in Ubuntu worked for me) ;-)

**Comment by bcarrier** [comment]
Thanks.  I noticed this too.  I think Autopsy runs when it is only 'set', but the bash script wasn't happy. I think we can just change the script.

**Comment by bcarrier** [comment]
Updated documentation to reflect that you sometimes need to log out before the script sees JAVA_HOME.

https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt

**Comment by TheWhiteWolf-001** [comment]
I have the same problem: 
```

~/Download/autopsy-4.14.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
~/Download/autopsy-4.14.0$ export JAVA_HOME
~/Download/autopsy-4.14.0$ sudo sh unix_setup.sh 
---------------------------------------------
Checking prerequisites and preparing Autopsy:
---------------------------------------------
Checking for PhotoRec...found in /usr/bin
Checking for Java...ERROR: JAVA_HOME environment variable must be defined.
~/Download/autopsy-4.14.0$ 
```

**Comment by dkarpo** [comment]
Try running your 'sh unix_setup.sh' as your regular user without the sudo. I believe the issue you are seeing is that the JAVA_HOME environment variable you set isn't retained in the sudo shell.

**Comment by TheWhiteWolf-001** [comment]
> Try running your 'sh unix_setup.sh' as your regular user without the sudo. I believe the issue you are seeing is that the JAVA_HOME environment variable you set isn't retained in the sudo shell.

I tried... but It doesn't work

**Comment by dkarpo** [comment]
What distro are you o?. Can you post the output of your following?

```sh
$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
$ export JAVA_HOME
$ echo $JAVA_HOME
```
Also:

```sh
$ which sh
$ ls -la /bin/sh (I'm assuming the above 'which sh' will show '/bin/sh' so adjust this line as per the 'which' output)
```
Failing all that, $JAVA_HOME is not retained when you log out and log back in after setting it?

**Comment by TheWhiteWolf-001** [comment]
> What distro are you on? Can you post the output of your following?
> 
> ```shell
> $ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
> $ export JAVA_HOME
> $ echo $JAVA_HOME
> ```
> 
> Also:
> 
> ```shell
> $ which sh
> $ ls -la /bin/sh (I'm assuming the above 'which sh' will show '/bin/sh' so adjust this line as per the 'which' output)
> ```
> 
> Failing all that, $JAVA_HOME is not retained when you log out and log back in after setting it?

I am using Ubuntu... 

So... this is the result: 

```
~/Download/autopsy-4.14.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
~/Download/autopsy-4.14.0$ export JAVA_HOME
~/Download/autopsy-4.14.0$ echo JAVA_HOME
JAVA_HOME

And...

~/Download/autopsy-4.14.0$ which sh
/usr/bin/sh
~/Download/autopsy-4.14.0$ ls -la /bin/sh
lrwxrwxrwx 1 root root 4 apr  6 16:54 /bin/sh -> dash

```



```

**Comment by dkarpo** [comment]
When you 'echo $JAVA_HOME' you need to include the $ in the front and post
the results.

For the 'which sh', yours points to /usr/bin/sh, so can you post the output
for 'ls -la /usr/bin/sh'.

**Comment by TheWhiteWolf-001** [comment]
```
~$ echo $JAVA_HOME
/usr/bin/java
~$ ls -la /usr/bin/sh
lrwxrwxrwx 1 root root 4 apr  6 16:54 /usr/bin/sh -> dash 
```

**Comment by TheWhiteWolf-001** [comment]
These are the difference between sudo and not sudo commands:

```
~/Download/autopsy-4.14.0$ sudo sh unix_setup.sh 
---------------------------------------------
Checking prerequisites and preparing Autopsy:
---------------------------------------------
Checking for PhotoRec...found in /usr/bin
Checking for Java...ERROR: JAVA_HOME environment variable must be defined.
~/Download/autopsy-4.14.0$ sh unix_setup.sh 
---------------------------------------------
Checking prerequisites and preparing Autopsy:
---------------------------------------------
Checking for PhotoRec...found in /usr/bin
Checking for Java...ERROR: Java was not found in /usr/bin/java. 
```

**Comment by TheWhiteWolf-001** [comment]
Nobody has a solution?

**Comment by dkarpo** [comment]
If you run unix_setup.sh with sudo it's not going to work since you lose that $JAVA_HOME environment variable. Just run is as a regular user with a 'sh unix_setup.sh'.

It looks like you need to confirm your Java installation is functional as it might be broken. What is the output of '/usr/bin/java -version'? What is the output of 'update-alternatives --display java'?

**Comment by TheWhiteWolf-001** [comment]
```
~/Download/autopsy-4.14.0$ /usr/bin/java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+8)
OpenJDK 64-Bit Server VM (build 14.0.1+8, mixed mode, sharing)
~/Download/autopsy-4.14.0$ update-alternatives --display java
java - modalità automatica
  la versione migliore del collegamento è /usr/lib/jvm/bellsoft-java14-full-amd64/bin/java
  il collegamento attualmente punta a /usr/lib/jvm/bellsoft-java14-full-amd64/bin/java
  il collegamento java è /usr/bin/java
  slave java.1 è /usr/share/man/man1/java.1
  slave java.1.gz è /usr/share/man/man1/java.1.gz
/usr/lib/jvm/bellsoft-java14-amd64/bin/java - priorità 21400012
  slave java.1: /usr/lib/jvm/bellsoft-java14-amd64/man/man1/java.1
/usr/lib/jvm/bellsoft-java14-full-amd64/bin/java - priorità 21400013
  slave java.1: /usr/lib/jvm/bellsoft-java14-full-amd64/man/man1/java.1
/usr/lib/jvm/bellsoft-java8-amd64/bin/java - priorità 20802522
  slave java.1: /usr/lib/jvm/bellsoft-java8-amd64/man/man1/java.1
/usr/lib/jvm/bellsoft-java8-full-amd64/bin/java - priorità 20802523
  slave java.1: /usr/lib/jvm/bellsoft-java8-full-amd64/man/man1/java.1
/usr/lib/jvm/java-11-openjdk-amd64/bin/java - priorità 1111
  slave java.1.gz: /usr/lib/jvm/java-11-openjdk-amd64/man/man1/java.1.gz
/usr/lib/jvm/java-14-openjdk-amd64/bin/java - priorità 1411
  slave java.1.gz: /usr/lib/jvm/java-14-openjdk-amd64/man/man1/java.1.gz
/usr/lib/jvm/java-8-openjdk-amd64/bin/java - priorità 1000
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java - priorità 1081
  slave java.1.gz: /usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/java.1.gz
```

**Comment by TheWhiteWolf-001** [comment]
> If you run unix_setup.sh with sudo it's not going to work since you lose that $JAVA_HOME environment variable. Just run it as a regular user with a 'sh unix_setup.sh'.

I get the same output

**Comment by dkarpo** [comment]
Thanks. Can you try the following?

```sh
$ JAVA_HOME=/usr/lib/jvm/bellsoft-java8-amd64
$ export JAVA_HOME
$ echo $JAVA_HOME
$ sh unix_setup.sh
```

**Comment by TheWhiteWolf-001** [comment]
I don't understand!

```
~/Download/autopsy-4.14.0$ JAVA_HOME=/usr/lib/jvm/bellsoft-java8-amd64
~/Download/autopsy-4.14.0$ export JAVA_HOME
~/Download/autopsy-4.14.0$ echo $JAVA_HOME
/usr/lib/jvm/bellsoft-java8-amd64
~/Download/autopsy-4.14.0$ sh unix_setup.sh
---------------------------------------------
Checking prerequisites and preparing Autopsy:
---------------------------------------------
Checking for PhotoRec...found in /usr/bin
Checking for Java...ERROR: Java was not found in /usr/lib/jvm/bellsoft-java8-amd64.

```

**Comment by dkarpo** [comment]
Hmm. What is the output of the following?

```sh
$ dpkg -l '*bellsoft*'
$ ls -la /usr/lib/jvm/bellsoft-java8-amd64
$ ls -la /usr/lib/jvm/bellsoft-java8-amd64/bin/jav*
```

**Comment by TheWhiteWolf-001** [comment]
```
$ dpkg -l '*bellsoft*'
Voluto=U (non noto)/I (installato)/R (rimosso)/P (rimosso totale)/H (in attesa)
| Stato=Non/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(nessuno)/R (reinstallazione richiesta) (Stato,Err: maiuscolo=grave)
||/ Nome                 Versione     Architettura Descrizione
+++-====================-============-============-============================
ii  bellsoft-java14      14.0.1+8     amd64        BellSoft Liberica is a build
ii  bellsoft-java14-full 14.0.1+8     amd64        BellSoft Liberica is a build
ii  bellsoft-java8       1.8.0.252+9  amd64        BellSoft Liberica is a build
ii  bellsoft-java8-full  1.8.0.252+9  amd64        BellSoft Liberica is a build
$ ls -la /usr/lib/jvm/bellsoft-java8-amd64
totale 51252
drwxr-xr-x  9 root  root      4096 apr 16 10:44 .
drwxr-xr-x 13 10668 10668     4096 apr 17 14:43 ..
-rw-r--r--  1 root  root      1522 apr 12 09:24 ASSEMBLY_EXCEPTION
drwxr-xr-x  2 root  root      4096 apr 16 10:44 bin
drwxr-xr-x 10 root  root      4096 apr 16 10:44 demo
drwxr-xr-x  3 root  root      4096 apr 16 10:44 include
drwxr-xr-x  4 root  root      4096 apr 16 10:44 jre
drwxr-xr-x  3 root  root      4096 apr 16 10:44 lib
-rw-r--r--  1 root  root     19274 apr 12 09:24 LICENSE
drwxr-xr-x  4 root  root      4096 apr 16 10:44 man
-rw-r--r--  1 root  root       255 apr 15 17:33 readme.txt
-rw-r--r--  1 root  root       239 apr 12 09:25 release
drwxr-xr-x 10 root  root      4096 apr 16 10:44 sample
-rw-r--r--  1 root  root  52253480 apr 12 09:24 src.zip
-rw-r--r--  1 root  root    153250 apr 12 09:24 THIRD_PARTY_README
$ ls -la /usr/lib/jvm/bellsoft-java8-amd64/bin/jav*
-rwxr-xr-x 1 root root 8728 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/java
-rwxr-xr-x 1 root root 8856 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/javac
-rwxr-xr-x 1 root root 8856 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/javadoc
-rwxr-xr-x 1 root root 8856 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/javah
-rwxr-xr-x 1 root root 8856 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/javap
-rwxr-xr-x 1 root root 2806 apr 12 09:24 /usr/lib/jvm/bellsoft-java8-amd64/bin/java-rmi.cgi
```

**Comment by dkarpo** [comment]
Okay, I'm making a wild guess that your 'unix_setup.sh' is corrupt, or has some funky encoded characters, or something is odd with your shell! Something is causing your shell to fail when it tests for Java and the Java test is simply:

```sh
# Verify Java was installed and configured
echo -n "Checking for Java..."
if [ -n "$JAVA_HOME" ];  then
    if [ -x "$JAVA_HOME/bin/java" ]; then
        echo "found in $JAVA_HOME"
    else
        echo "ERROR: Java was not found in $JAVA_HOME."
        exit 1
    fi
<snip>
```

So, in your case it checks that the Java file exists and is executable (/usr/lib/jvm/bellsoft-java8-amd64/bin/java) and should carry on from there. However, when you run it, it explodes and never gets past this simple check in the shell script.

My suggestion is to start from scratch. Remove your Github 'autopsy' folder, then clone autopsy again and try run 'unix_setup.sh' again. For reference the hash for 'unix_setup.sh' should be as follows:

```sh
$ sha256sum unix_setup.sh 
e6fea357e2a450e2ff989e002a4032503cf660b42765a731fbe81fec5ace42e2  unix_setup.sh
```

**Comment by TheWhiteWolf-001** [comment]
Thank you so much! I resolved the JAVA_HOME problem. 
But now I have another problem:

```
$ sh unix_setup.sh 
---------------------------------------------
Checking prerequisites and preparing Autopsy:
---------------------------------------------
Checking for PhotoRec...found in /usr/bin
Checking for Java...found in /usr/lib/jvm/bellsoft-java14-full-amd64
Checking for Sleuth Kit Java bindings...ERROR: sleuthkit-4.9.0.jar not found in /usr/share/java/ or /usr/local/share/java/.
Please install the Sleuth Kit Java bindings file.
See https://github.com/sleuthkit/sleuthkit/releases.

The sleuthkit 4.9 there isn't in the "official releases". So I get it from the repository https://github.com/sleuthkit/sleuthkit, but for it doesn't work "make" command.
```

**Comment by TheWhiteWolf-001** [comment]
Thank you so much!
I downloaded autopsy from scratch and now it works!

**Comment by Operator0x0A** [comment]
I tried this fix, but it does not work for me. Everything previous to this last step was the same.

**Comment by xFraylin** [comment]
> Hello.
> 
> The current instructions for Autopsy under Linux Requisites reference the Oracle docs for setting JAVA_HOME. The problem is that the JAVA_HOME variable needs to be set, as well as exported, so that it is available to child processes during unix_setup.sh. Recommend updating the instructions to include this export. ie:
> 
> dk@anubis:~/src/autopsy-4.6.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
> dk@anubis:~/src/autopsy-4.6.0$ echo $JAVA_HOME
> /usr/lib/jvm/java-8-openjdk-amd64
> dk@anubis:~/src/autopsy-4.6.0$ sh unix_setup.sh
> /usr/bin/photorec found
> ERROR: JAVA_HOME environment variable must be defined
> 
> With JAVA_HOME set and exported, the unix_setup.sh will run correctly:
> 
> dk@anubis:~/src/autopsy-4.6.0$ JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
> dk@anubis:~/src/autopsy-4.6.0$ export JAVA_HOME
> dk@anubis:~/src/autopsy-4.6.0$ sh unix_setup.sh 
> /usr/bin/photorec found
> Java found in /usr/lib/jvm/java-8-openjdk-amd64
> /usr/share/java/sleuthkit-4.6.0.jar found
> Copying into the Autopsy directory
> Autopsy is now configured. You can execute bin/autopsy to start it

I works for me, Thank you
