### ISSUE TITLE
Windows 10 - Autopsy 4.6 problem with opening case

### ISSUE THREAD

**Issue by jgzone** [sleuthkit/autopsy#3582]
Hello
I'm working on Windows 10 64 bit and Autopsy 4.6 64 bit. Halfway through working at case I'm update Autopsy version from 4.5 to 4.6. I've got big problem, because when I open case, Autopsy send me "Failed to read case metadata". I've tried many things, uninstal, clear registry keys, etc. This situation is repeated for each project/case.

Copy info from About:
Product Version: Autopsy 4.6.0 (RELEASE) Sleuth Kit Version: 4.6.0 Netbeans RCP Build: 201609300101 Java: 1.8.0_152; Java HotSpot(TM) 64-Bit Server VM 25.152-b16 System: Windows 10 version 10.0 running on amd64; Cp1250; pl_PL (autopsy) Userdir: C:\Users\***********\AppData\Roaming\autopsy

`SEVERE: Error opening case with metadata file path C:\Users\**********\Desktop\12\12.aut
org.sleuthkit.autopsy.casemodule.CaseActionException: Failed to read case metadata.
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:568)
	org.sleuthkit.autopsy.casemodule.OpenRecentCasePanel.lambda$openCase$1(OpenRecentCasePanel.java:132)
	java.lang.Thread.run(Unknown Source)
org.sleuthkit.autopsy.casemodule.CaseMetadata$CaseMetadataException: Error reading from case metadata file C:\Users\*************\Desktop\12\12.aut
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:568)
	org.sleuthkit.autopsy.casemodule.OpenRecentCasePanel.lambda$openCase$1(OpenRecentCasePanel.java:132)
	java.lang.Thread.run(Unknown Source)
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:568)
	org.sleuthkit.autopsy.casemodule.OpenRecentCasePanel.lambda$openCase$1(OpenRecentCasePanel.java:132)
	java.lang.Thread.run(Unknown Source)`

Please give me some tip for fix it.

**Comment by rcordovano** [comment]
@jgzone, thanks for sending along the exception, it is very helpful. Autopsy 4.6 is having a problem parsing the XML in the case metadata file, which is the 12.aut file in the case folder that you select to open the case. I am wondering if Autopsy was closed while the file was being written, so that it is corrupted. You can open the file yourself in any text editor to try to see if the XML has become malformed. Or if you are able to send me the 12.aut file, I can look at it for you.

**Comment by jgzone** [comment]
Hi Richard.
Thank for your help. This problem don't only concerned this case but other too.
I have fix it :) The problem was in using polish character in case details descriptions. He was so mundane that he didn't come to my mind.
Thank you very much for your help. I will keep you informed of other issues.
 
Geers
 
W dniu 2018-03-21 17:41:00 użytkownik Richard Cordovano <notifications@github.com> napisał:
@jgzone, thanks for sending along the exception, it is very helpful. Autopsy 4.6 is having a problem parsing the XML in the case metadata file, which is the 12.aut file in the case folder that you select to open the case. I am wondering if Autopsy was closed while the file was being written, so that it is corrupted. You can open the file yourself in any text editor to try to see if the XML has become malformed. Or if you are able to send me the 12.aut file, I can look at it for you.

**Comment by rcordovano** [comment]
@jgzone, I'm glad you worked that out. I will go ahead and close out this issue, thanks!

**Comment by bcarrier** [comment]
This seems like a bug though in Autopsy.  We probably are not encoding the non-Latin characters properly.  We'll look into this.

**Comment by CarlosLannister** [comment]
Same here with 4.10.0. My surname has a non latin character. Everything when I remove the character.

**Comment by MUTURIJOHN** [comment]
I'm having this error message every time i try to use my autopsy 4.19.2. Error getting interesting files sets from settings file. What could be the issue?
