### ISSUE TITLE
Timezone Typo

### ISSUE THREAD

**Issue by megan201296** [sleuthkit/autopsy#3727]
Running 4.6.0 and when I was selecting a timezone I noticed that what is supposed to be `UTC` (I am assuming) is labeled `UCT`. Simple typo but worth mentioning. See screenshot.

![screen shot 2018-04-28 at 12 24 37 pm](https://user-images.githubusercontent.com/19668285/39399425-065b528e-4ae3-11e8-8220-cababb3cfb97.png)

**Comment by ffsantos92** [comment]
Not a typo because it's locale-dependent.

**Comment by bcarrier** [comment]
Agreed.  Mine is UTC:

![image](https://user-images.githubusercontent.com/856501/40250985-f7134016-5aa5-11e8-85e7-4210c8dbffc0.png)
