### ISSUE TITLE
File tagging with module

### ISSUE THREAD

**Issue by AlexXandreE** [sleuthkit/autopsy#3729]
Hi everyone,

As noted in the documentation: 
'''
Deprecated since API 3.1
Avoid the usage of the below as the behavior has changed since the update to 3.1. TSK_TAG_FILE for example will not separate them by TSK_TAG_NAME anymore and they will all get grouped together as "Tagged Files" under extracted content.

BlackboardArtifact.ARTIFACT_TYPE

TSK_TAG_ARTIFACT
TSK_TAG_FILE
'''

Is there a way to prevent tagged files from stacking under **results -> extracted content -> tagged files**?

Or is the only workaround to just make TSK_INTERESTING_FILE_HIT/ TSK_INTERESTING_ARTIFACT_HIT ?

Thanks for the support, Alexandre F.

**Comment by bcarrier** [comment]
Our recommendation at this point is to use TSK_INTERESTING artifacts when a module flags something as being suspicious. And we use tags for things that the user explicitly marks.  There are now dedicated tables in the DB for tags and that is why the TAG artifacts were deprecated.

Does that answer your question?

**Comment by AlexXandreE** [comment]
I see, it does thank you
