### ISSUE TITLE
FIX: Autopsy 3.0.8 Java "Cannot create Java Virtual Machine"

### ISSUE THREAD

**Issue by staridlabs** [sleuthkit/autopsy#379]
Go to C:\Program Files\Autopsy-3.0.8\etc

Edit autopsy.conf (May want to set user permissions to write temporarily while troubleshooting)

Remove -Xdock:name=Autopsy

Save file

Close.

You do not need to modify memory settings on 64 bit autopsy.

**Comment by bcarrier** [comment]
NOTE: This was "fixed again" in #3401.  Somehow the previous fix never made it back to the develop branch since it was done as a last minute fix during a release.
