### ISSUE TITLE
JVM crashed after logging 30 times: TskCoreException / Shift is too large

### ISSUE THREAD

**Issue by goorgoorlou** [sleuthkit/autopsy#3995]
JVM crashed (during night-long operation) after logging 30 times the below exception. Logfile likely truncated.

Looks like TSK/Autopsy did not like something on the disk image (EnCase) I was ingesting.

Product Version: Autopsy 4.7.0 (RELEASE) 
Sleuth Kit Version: 4.6.1 
Netbeans RCP Build: 201609300101 
Java: 1.8.0_152; Java HotSpot(TM) 64-Bit Server VM 25.152-b16 
System: Windows 10 version 10.0 running on amd64; Cp1252; en_US (autopsy)

`
INFO: Starting periodic searches
2018-07-26 22:17:35.555 org.sleuthkit.autopsy.keywordsearch.SearchRunner$PeriodicSearchTask run
INFO: Executing periodic search for search job 1
2018-07-27 00:06:32.964 org.sleuthkit.autopsy.modules.filetypeid.FileType$Signature containedIn
WARNING: Error reading from file with objId = 2988412
org.sleuthkit.datamodel.TskCoreException: Error extracting file from image (ntfs_uncompress_compunit: Shift is too large: 60) (2287401 - type: 128  id: 3  Status: Deleted)
	org.sleuthkit.datamodel.SleuthkitJNI.readFileNat(Native Method)
	org.sleuthkit.datamodel.SleuthkitJNI.readFile(SleuthkitJNI.java:803)
	org.sleuthkit.datamodel.FsContent.readInt(FsContent.java:215)
	org.sleuthkit.datamodel.AbstractFile.read(AbstractFile.java:770)
	org.sleuthkit.autopsy.modules.filetypeid.FileType$Signature.containedIn(FileType.java:343)
	org.sleuthkit.autopsy.modules.filetypeid.FileType.matches(FileType.java:138)
	org.sleuthkit.autopsy.modules.filetypeid.FileTypeDetector.detectAutopsyDefinedType(FileTypeDetector.java:302)
	org.sleuthkit.autopsy.modules.filetypeid.FileTypeDetector.getMIMEType(FileTypeDetector.java:216)
	org.sleuthkit.autopsy.keywordsearch.KeywordSearchIngestModule$Indexer.indexFile(KeywordSearchIngestModule.java:523)
	org.sleuthkit.autopsy.keywordsearch.KeywordSearchIngestModule$Indexer.access$100(KeywordSearchIngestModule.java:416)
	org.sleuthkit.autopsy.keywordsearch.KeywordSearchIngestModule.process(KeywordSearchIngestModule.java:283)
	org.sleuthkit.autopsy.ingest.FileIngestPipeline$PipelineModule.process(FileIngestPipeline.java:230)
	org.sleuthkit.autopsy.ingest.FileIngestPipeline.process(FileIngestPipeline.java:129)
	org.sleuthkit.autopsy.ingest.DataSourceIngestJob.process(DataSourceIngestJob.java:802)
	org.sleuthkit.autopsy.ingest.FileIngestTask.execute(FileIngestTask.java:44)
	org.sleuthkit.autopsy.ingest.IngestManager$ExecuteIngestJobTasksTask.run(IngestManager.java:876)
	java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	java.util.concurrent.FutureTask.run(Unknown Source)
	java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	java.lang.Thread.run(Unknown Source)
`

Please let me know if you need additional information. I'll try to reproduce and let you know.
Best regards.

**Comment by rcordovano** [comment]
@goorgoorlou, Autopsy tech lead responding. I talked to the engineer on my team who currently does most of our Sleuth Kit level work. She said the following:

"The error is displayed when the data is corrupt - in the error above it apparently wanted to shift something left by 60 positions. It's hard to tell from just that one error, but my guess would be that the shift errors are just telling us that his image is really messed up and something else we don't check for caused the crash."

**Comment by goorgoorlou** [comment]
Thank you!
Should Autopsy not gracefully handle the error, instead of crashing? 
As the problem is on my side, please feel free to close this issue.

**Comment by rcordovano** [comment]
Ideally, the Sleuth Kit would propagate an exception to Autopsy, which could then handle the error gracefully. But TSK is not perfectly robust (yet ;-) ). Given that the machine crashed, it is almost certain that there was an access violation, i.e., a pointer was loaded with an invalid memory address and then dereferenced. 

If you are able to share the input data source with us, we can run with debugger(s) and figure out what is going on, and look for a fix.

Another option is to run the executable with the command line option: 

-XX:+CreateMinidumpOnCrash 

You can then look in the working directory for files that start with hs_err_pid (full name would be of the form hs_err_pid[process id number].log. If you send us the crash dump file, we should be able to extract a stack trace that would tell us where things went bad in TSK, and we could then try to work back from there to deduce what data structures were corrupted, i.e., populated with bad data.

**Comment by goorgoorlou** [comment]
Unfortunately, I cannot share the analysed image, but I'll add the XX to the JVM command line and next time it crashes, I'll provide the info. I'll close this issue to not clutter your tracker. Thank you for maintaining FOSS tools!
