### ISSUE TITLE
Python Module Error Window

### ISSUE THREAD

**Issue by mrpumba2147** [sleuthkit/autopsy#4070]
With using 4.8 and the Python module, I keep getting this error message.  I have used the same python module with 4.7 and no errors.  Although I get an error, I am able to proceed with ingesting..
![imgpsh_mobile_save](https://user-images.githubusercontent.com/16866418/44695106-650fdc80-aa3f-11e8-9550-bcee8277552f.jpg)

**Comment by markmckinnon** [comment]
Since these are all my modules I will take a look at this. I have not tested my modules against 4.8 yet.

**Comment by markmckinnon** [comment]
The message means that it could not read the job settings for the ingest modules.  If you go into the directory c:\users\<username>\appdata\roaming\autopsy\config\IngestModuleSettings  and then remove files from the directories org.sleuthkit.autopsy.casemodule.AddImageWizardIngestConfigPanel and org.sleuthkit.autopsy.ingest.RunIngestModulesDialog that look like the following 
org.python.proxies.cuckoo$CuckooIngestModuleFactory.settings then you should not get the message anymore.  The files will be recreated on the next run.

**Comment by mrpumba2147** [comment]
This cleared it initially until I tried to use volatility module and the issue happened again.  Possibly that is the issue?  Will keep checking out the modules and let you know what causes it should it happen again with others.

**Comment by mrpumba2147** [comment]
Still getting the error as above but it will still process.

**Comment by markmckinnon** [comment]
This is fixed with the newest plugins from my github repo.  Install the updated modules and you will not get this error again.  This should be closed.  If you continue to get this error after you have updated the plugins then reopen an issue in my github repo.

**Comment by markmckinnon** [comment]
Closed as fixed.
