### ISSUE TITLE
Can't register on http://forum.sleuthkit.org

### ISSUE THREAD

**Issue by jdg68** [sleuthkit/autopsy#4262]
Hi,

The Captcha is broken on register...

![image](https://user-images.githubusercontent.com/42742559/48076359-45650500-e1a2-11e8-8537-3879fe12d371.png)

Thanks,

Jon

**Comment by marinerooo** [comment]
I hope they fix it soon. Today I tried to register and I could not for the captcha, that's why I had to open a question here.

**Comment by bcarrier** [comment]
We have setup a new forum.  Please use this one instead:

https://sleuthkit.discourse.group/
