### ISSUE TITLE
Request: APFS functions

### ISSUE THREAD

**Issue by roswitina** [sleuthkit/autopsy#4432]
I found this: 

https://www.blackbagtech.com/blog/2018/12/19/present-santa-apfs-providing-apfs-support-sleuth-kit-framework/

Is this built into Autopsy?

**Comment by onchari** [comment]
I will be also interested to see the implementation of this

**Comment by markmckinnon** [comment]
Yes this has been implemented in the sleuthkit which Autopsy is built on.  Closing as resolved.
