### ISSUE TITLE
Registry module will not install

### ISSUE THREAD

**Issue by mrpumba2147** [sleuthkit/autopsy#4457]
I'm trying to install the registry by William and receive an error (see attached pic).  It will ot allow me to proceed further and the only option is to cancel.  I'm running Win 10 Autopsy 4.9.1
![registry module](https://user-images.githubusercontent.com/16866418/51074289-7999ed80-164b-11e9-8fac-78bc7be93b10.PNG)

**Comment by rcordovano** [comment]
@mrpumba2147, I will see that this gets resolved. I will notify you when the fix is completed. Did you download the compiled module or build from source?

**Comment by mrpumba2147** [comment]
It is a download from the third party modules site. Listed as registry virewe module.  Mark McKinnon sent me the updated module and that works. This can be closed

**Comment by bcarrier** [comment]
You can also get the updated version from here:

https://github.com/sleuthkit/Autopsy-WindowsRegistryIngestModule/releases
