### ISSUE TITLE
Autopsy install: sleuthkit.jar file not found _ubuntu 18.10

### ISSUE THREAD

**Issue by NeuSleuth** [sleuthkit/autopsy#4472]
I'm completely new to Ubuntu.
I've installed The SleuthKit, sleuthkit-java_4.6.0-1_amd64.deb
When attempting to install Autopsy, I get the error.

osboxes@osboxes:/media/sf_VM_shared/Autopsy/autopsy-4.10.0$ ./unix_setup.sh
photorec found
Java found in /usr/lib/jvm/java-8-oracle
sleuthkit.jar file not found
exiting ..

**Comment by cdaly2** [comment]
The Autopsy Download page (https://www.sleuthkit.org/autopsy/download.php) has a broken link to a file (https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.6.5/sleuthkit-java_4.6.5-1_amd64.deb).

This deb file is missing from the sleuthkit-4.6.5 release and Autopsy 4.10.0 refuses to run without it.

However, the sleuthkit-java_4.6.4-1 release does have the deb file and if that file is renamed to sleuthkit-java_4.6.5-1_amd64.deb then Autopsy 4.10.0 seems to work flawlessly on Ubuntu 18.04.

**Comment by bcarrier** [comment]
Sorry, this release got a bit out of sync with the Linux release. The .deb file has now been uploaded, so the link now works.  

But, it looks like the unix_setup.sh script was not updated to pull in the new version.  So, there could be a lurking 2nd issue.

**Comment by bcarrier** [comment]
Never  mind about unix_setup.sh not getting updated.  I forgot that it gets updated at build time and not checked in.  I'll fix that though for consistency.
