### ISSUE TITLE
where is sleuthkit-java_4.6.6-1_amd64.deb?

### ISSUE THREAD

**Issue by andy7002** [sleuthkit/autopsy#4866]
"https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.6.5/sleuthkit-java_4.6.6-1_amd64.deb", this url cannot reached, how can i download sleuthkit-java_4.6.6-1_amd64.deb?

**Comment by bcarrier** [comment]
https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.6.6/sleuthkit-java_4.6.6-1_amd64.deb
