### ISSUE TITLE
"Error opening Image Gallery databases" Autopsy 4.11 + Ubuntu 18.04

### ISSUE THREAD

**Issue by mfrade** [sleuthkit/autopsy#4943]
Whenever I create a case on Autopsy running on Ubuntu I get the error bellow and I'm not able to view any media files inside Autopsy. Any hints on how to solve this?

SEVERE: Image Gallery Database Update Service failed to open case resources for DellComputer
java.util.concurrent.ExecutionException: org.sleuthkit.autopsy.appservices.AutopsyService$AutopsyServiceException: Error opening Image Gallery databases
	java.util.concurrent.FutureTask.report(FutureTask.java:122)
	java.util.concurrent.FutureTask.get(FutureTask.java:192)
	org.sleuthkit.autopsy.casemodule.Case.openAppServiceCaseResources(Case.java:2222)
	org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1855)
	org.sleuthkit.autopsy.casemodule.Case.lambda$open$5(Case.java:1743)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
org.sleuthkit.autopsy.appservices.AutopsyService$AutopsyServiceException: Error opening Image Gallery databases
	java.util.concurrent.FutureTask.report(FutureTask.java:122)
	java.util.concurrent.FutureTask.get(FutureTask.java:192)
	org.sleuthkit.autopsy.casemodule.Case.openAppServiceCaseResources(Case.java:2222)
	org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1855)
	org.sleuthkit.autopsy.casemodule.Case.lambda$open$5(Case.java:1743)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
org.sleuthkit.datamodel.TskCoreException: Error altering table  image_gallery_groups with SQL = ALTER TABLE image_gallery_groups  ADD COLUMN is_analyzed integer DEFAULT 1 
	java.util.concurrent.FutureTask.report(FutureTask.java:122)
	java.util.concurrent.FutureTask.get(FutureTask.java:192)
	org.sleuthkit.autopsy.casemodule.Case.openAppServiceCaseResources(Case.java:2222)
	org.sleuthkit.autopsy.casemodule.Case.open(Case.java:1855)
	org.sleuthkit.autopsy.casemodule.Case.lambda$open$5(Case.java:1743)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)

**Comment by rcordovano** [comment]
This is a known issue that appears to us to be a SQLite bug. A workaround will be included in the Autopsy 4.12.0, which is almost ready for release. We have experienced this as an intermittent issue, so you might have some luck just closing the case and re-opening it.

**Comment by mfrade** [comment]
On my system I never was able to make it work on Linux and it also happened on version 4.10. 
Anyway, I'm glad to know that a new version is coming soon and I'm looking forward to try it.

**Comment by markmckinnon** [comment]
Closing this as fixed in Autopy 4.12.0.  If this is still an issue please reopen .
