### ISSUE TITLE
BUILD FAILED "class file has wrong version 55.0, should be 52.0"

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5044]
I have an error in the build.

But I do not know why this error occurs.

I want you to give me a solution.

> projectized-common.compile:
>     [mkdir] Created dir: C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\build\classes
>  [nb-javac] Compiling 997 source files to C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\build\classes
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\httpclient-4.2.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\commons-logging-1.1.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\commons-codec-1.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\httpcore-4.2.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\httpmime-4.2.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\slf4j-api-1.7.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jcl-over-slf4j-1.7.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jdom2-2.0.4.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\protobuf-java-2.5.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\guava-17.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jna-4.1.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\esri-geometry-api-2.0.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jackson-core-2.6.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\commons-vfs2-2.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jsoup-1.7.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\jj2000-5.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-lang3-3.8.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jempbox-1.8.16.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jackcess-2.2.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jericho-html-3.3.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\cdm-4.5.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\httpservices-4.5.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\xz-1.8.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-validator-1.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sis-utility-0.8.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jna-5.1.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\boilerpipe-1.1.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jbig2-imageio-3.0.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jsoup-1.11.3.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sevenzipjbinding.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\apache-mime4j-dom-0.8.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\mchange-commons-java-0.2.9.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\pdfbox-2.0.13.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jackson-databind-2.9.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jai-imageio-core-1.4.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jcl-over-slf4j-1.7.25.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\curator-recipes-2.8.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\tika-core-1.20.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\tagsoup-1.2.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\StixLib.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jackson-core-2.9.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sis-metadata-0.8.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\bcprov-jdk15on-1.60.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\parso-2.0.10.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\json-simple-1.1.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\metadata-extractor-2.11.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\apache-mime4j-core-0.8.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jmatio-1.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sleuthkit-postgresql-4.6.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\tika-parsers-1.20.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\asm-7.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-pool2-2.4.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-io-2.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jdom-2.0.5-contrib.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\SparseBitSet-1.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\openjson-1.0.10.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\isoparser-1.1.22.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\c3p0-0.9.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\xmpcore-5.1.3.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\zookeeper-3.4.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\javax.activation-1.2.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-csv-1.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jdom-2.0.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\rome-1.12.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jackson-annotations-2.9.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\javax.annotation-api-1.3.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\vorbis-java-core-0.8.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\netcdf4-4.5.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\java-libpst-0.8.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sis-netcdf-0.8.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\curator-framework-2.8.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sentiment-analysis-parser-0.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\commons-dbcp2-2.1.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jgraphx-v3.8.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\juniversalchardet-1.0.3.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jython-standalone-2.7.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\uimafit-core-2.4.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jackcess-encrypt-2.1.4.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jhighlight-1.0.3.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\junrar-2.0.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jul-to-slf4j-1.7.25.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\postgresql-9.4.1211.jre7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\slf4j-api-1.7.25.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\geoapi-3.0.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\httpmime-4.5.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\jdom2-2.0.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\httpclient-4.5.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\uimaj-core-3.0.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\curator-client-2.8.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\sqlite-jdbc-3.25.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\cxf-rt-rs-client-3.3.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\pdfbox-tools-2.0.13.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\grib-4.5.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\fontbox-2.0.13.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\activemq-all-5.11.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\dec-0.1.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\build\cluster\modules\ext\Rejistry-1.1-SNAPSHOT.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\dd-plist-1.20.jar": no such file or directory
>  [nb-javac] C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\src\org\sleuthkit\autopsy\actions\AddBlackboardArtifactTagAction.java:32: error: cannot access BlackboardArtifact
>  [nb-javac] import org.sleuthkit.datamodel.BlackboardArtifact;
>  [nb-javac]                               ^
>  [nb-javac]   bad class file: C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\Core\release\modules\ext\sleuthkit-postgresql-4.6.7.jar(org/sleuthkit/datamodel/BlackboardArtifact.class)
>  [nb-javac]     class file has wrong version 55.0, should be 52.0
>  [nb-javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
> 
> BUILD FAILED
> C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\netbeans-plat\8.2\harness\suite.xml:187: The following error occurred while executing this line:
> C:\Users\ZeroTwo\Desktop\autopsy (2)\원본\autopsy\netbeans-plat\8.2\harness\common.xml:225: Compile failed; see the compiler error output for details.

**Comment by arcturus2** [comment]
@JungDonggun  did you find the solution to this issue in the end. I am having the same problem in my NetBeans project and can't figure out where the old references are even after a clean build. Thank you.
