### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5059]
The module org.jdesktop.layout has been deprecated
rojectized-common.compile:
    [mkdir] Created dir: C:\autopsy\Core\build\classes
 [nb-javac] Compiling 997 source files to C:\autopsy\Core\build\classes
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpclient-4.2.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-logging-1.1.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-codec-1.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpcore-4.2.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpmime-4.2.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\slf4j-api-1.7.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jcl-over-slf4j-1.7.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jdom2-2.0.4.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\protobuf-java-2.5.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\guava-17.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jna-4.1.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\esri-geometry-api-2.0.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jackson-core-2.6.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-vfs2-2.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jsoup-1.7.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jj2000-5.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-lang3-3.8.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jempbox-1.8.16.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jackcess-2.2.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jericho-html-3.3.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\cdm-4.5.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\httpservices-4.5.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\xz-1.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-validator-1.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sis-utility-0.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jna-5.1.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\boilerpipe-1.1.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jbig2-imageio-3.0.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jsoup-1.11.3.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sevenzipjbinding.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\apache-mime4j-dom-0.8.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\pdfbox-2.0.13.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jackson-databind-2.9.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jai-imageio-core-1.4.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jcl-over-slf4j-1.7.25.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\curator-recipes-2.8.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\tika-core-1.20.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\tagsoup-1.2.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\StixLib.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jackson-core-2.9.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sis-metadata-0.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\bcprov-jdk15on-1.60.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\parso-2.0.10.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\json-simple-1.1.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\metadata-extractor-2.11.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\apache-mime4j-core-0.8.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jmatio-1.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\tika-parsers-1.20.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\asm-7.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-pool2-2.4.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-io-2.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jdom-2.0.5-contrib.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\openjson-1.0.10.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\isoparser-1.1.22.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\xmpcore-5.1.3.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\zookeeper-3.4.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\javax.activation-1.2.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-csv-1.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jdom-2.0.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\rome-1.12.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jackson-annotations-2.9.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\javax.annotation-api-1.3.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\vorbis-java-core-0.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\netcdf4-4.5.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\java-libpst-0.8.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sis-netcdf-0.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\curator-framework-2.8.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sentiment-analysis-parser-0.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\commons-dbcp2-2.1.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jgraphx-v3.8.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\juniversalchardet-1.0.3.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jython-standalone-2.7.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\uimafit-core-2.4.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jackcess-encrypt-2.1.4.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jhighlight-1.0.3.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\junrar-2.0.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jul-to-slf4j-1.7.25.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\slf4j-api-1.7.25.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\geoapi-3.0.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\httpmime-4.5.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\jdom2-2.0.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\httpclient-4.5.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\uimaj-core-3.0.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\curator-client-2.8.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\cxf-rt-rs-client-3.3.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\pdfbox-tools-2.0.13.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\grib-4.5.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\fontbox-2.0.13.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\activemq-all-5.11.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\dec-0.1.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\Rejistry-1.1-SNAPSHOT.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\dd-plist-1.20.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\sevenzipjbinding-AllPlatforms.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\bcmail-jdk15on-1.60.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\vorbis-java-tika-0.8.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\grpc-context-1.19.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\gax-grpc-1.44.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\build\cluster\modules\ext\opencensus-api-0.19.2.jar": no such file or directory
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.NbBundleProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.ServiceProviderProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.util.NamedServiceProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.awt.ActionProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.api.annotations.common.proc.StaticResourceProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.filesystems.declmime.MIMEResolverProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.templates.TemplateProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.loaders.DataObjectFactoryProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.editor.mimelookup.CreateRegistrationProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.windows.TopComponentProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.openide.nodes.NodesAnnotationProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.intent.OpenUriHandlerProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.options.OptionsPanelControllerProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.sendopts.OptionAnnotationProcessor' less than -source '1.8'
 [nb-javac] warning: Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.settings.convertors.ConvertorProcessor' less than -source '1.8'
 [nb-javac] warning: No processor claimed any of these annotations: java.lang.FunctionalInterface,org.sleuthkit.autopsy.coreutils.ThreadConfined,com.google.common.eventbus.Subscribe,javax.annotation.Nonnull,javax.annotation.Nullable,com.google.gson.annotations.Expose,org.openide.windows.RetainLocation,javax.annotation.concurrent.ThreadSafe,javax.annotation.concurrent.GuardedBy,com.google.gson.annotations.SerializedName,com.google.common.annotations.Beta,javafx.fxml.FXML,javafx.beans.DefaultProperty,javax.annotation.concurrent.Immutable,com.sun.javafx.beans.IDProperty
 [nb-javac] warning: No processor claimed any of these annotations: javax.annotation.Generated
 [nb-javac] C:\autopsy\Core\src\org\sleuthkit\autopsy\communications\FiltersPanel.java:66: error: cannot find symbol
 [nb-javac] import org.sleuthkit.datamodel.CommunicationsFilter.MostRecentFilter;
 [nb-javac]                                                    ^
 [nb-javac]   symbol:   class MostRecentFilter
 [nb-javac]   location: class CommunicationsFilter
 [nb-javac] C:\autopsy\Core\src\org\sleuthkit\autopsy\communications\FiltersPanel.java:440: error: cannot find symbol
 [nb-javac]     private void setMostRecentFilter(MostRecentFilter filter) {
 [nb-javac]                                      ^
 [nb-javac]   symbol:   class MostRecentFilter
 [nb-javac]   location: class FiltersPanel
 [nb-javac] C:\autopsy\Core\src\org\sleuthkit\autopsy\communications\FiltersPanel.java:889: error: cannot find symbol
 [nb-javac]     private MostRecentFilter getMostRecentFilter() {
 [nb-javac]             ^
 [nb-javac]   symbol:   class MostRecentFilter
 [nb-javac]   location: class FiltersPanel
 [nb-javac] 3 errors
 [nb-javac] 17 warnings

BUILD FAILED
C:\autopsy\netbeans-plat\8.2\harness\suite.xml:187: The following error occurred while executing this line:
C:\autopsy\netbeans-plat\8.2\harness\common.xml:225: Compile failed; see the compiler error output for details.

Total time: 2 minutes 19 seconds

C:\autopsy>
C:\autopsy>
C:\autopsy>
C:\autopsy>

**Comment by rcordovano** [comment]
Your SleuthKit source code and your Autopsy source code are out of sync. That's what the "cannot find symbol" errors are caused by. The version of the Autopsy source you are using is expecting classes such as org.sleuthkit.datamodel.CommunicationsFilter.MostRecentFilter to exist in TSK Java bindings, but the version of TSK you are building against does not have those classes.

**Comment by utahaZZ** [comment]
Thanks for your support! :)

**Comment by utahaZZ** [comment]
> Your SleuthKit source code and your Autopsy source code are out of sync. That's what the "cannot find symbol" errors are caused by. The version of the Autopsy source you are using is expecting classes such as org.sleuthkit.datamodel.CommunicationsFilter.MostRecentFilter to exist in TSK Java bindings, but the version of TSK you are building against does not have those classes.

Thanks for your support! :)
