### ISSUE TITLE
The module org.jdesktop.layout has been deprecated Error

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5060]
Hi.

My operating system is Window

When building, I get an error "The module org.jdesktop.layout has been deprecated".

I hope you will give me a solution.

**Comment by rcordovano** [comment]
The warning "The module org.jdesktop.layout has been deprecated" does not stop the Autopsy source code from building. Based on compiler output in another issue you have opened, it appears that you are building a newer version of the Autopsy source code and an older version of the SleuthKit source code and the two versions are incompatible. I will close this issue and any further discussion can happen in the context of the other issue.
