### ISSUE TITLE
Is this an ignorable error?

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5073]
Hi I have a question.

I got a warning while building Autopsy.

Is this a warning you can ignore?

 
> projectized-common.compile:
>    [depend] Deleted 240 out of date files in 3 seconds
>  [nb-javac] Compiling 987 source files to C:\autopsy\Core\build\classes
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpclient-4.2.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-logging-1.1.1.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-codec-1.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpcore-4.2.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\httpmime-4.2.6.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\slf4j-api-1.7.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jcl-over-slf4j-1.7.7.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jdom2-2.0.4.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\protobuf-java-2.5.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\guava-17.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jna-4.1.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\esri-geometry-api-2.0.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jackson-core-2.6.5.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\commons-vfs2-2.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jsoup-1.7.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\jj2000-5.2.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
>  [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\dd-plist-1.20.jar": no such file or directory

**Comment by bcarrier** [comment]
Yes, those are fine. They eventually get resolved.

**Comment by utahaZZ** [comment]
@bcarrier Thanks so much!
