### ISSUE TITLE
"[nb-javac] warning: [path] bad path element"

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5079]
Hi.

I got this warning while building Autopsy.

Is this warning an ignorable error?

> projectized-common.compile:
   [depend] Deleted 183 out of date files in 2 seconds
 [nb-javac] Compiling 50 source files to C:\autopsy\KeywordSearch\build\classes
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\opennlp-tools-1.9.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\Core\release\modules\ext\dd-plist-1.20.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\httpclient-4.2.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\commons-logging-1.1.1.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\commons-codec-1.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\httpcore-4.2.5.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\httpmime-4.2.6.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\slf4j-api-1.7.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\jcl-over-slf4j-1.7.7.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\jdom2-2.0.4.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\jna-4.1.0.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\jsoup-1.7.2.jar": no such file or directory
 [nb-javac] warning: [path] bad path element "C:\autopsy\KeywordSearch\release\modules\ext\jj2000-5.2.jar": no such file or directory

**Comment by rcordovano** [comment]
Yes.

**Comment by utahaZZ** [comment]
@rcordovano Thanks for your support
