### ISSUE TITLE
Unicode error?

### ISSUE THREAD

**Issue by utahaZZ** [sleuthkit/autopsy#5142]
Hi.

I was working on changing Autopsy Text to Korean Language.

However, after changing the text, the text is broken like an image.

I want to know the solution.
![2019-08-27_17-24-21](https://user-images.githubusercontent.com/48436555/63754540-faaea800-c8ef-11e9-9cad-2b33460a6db0.png)

**Comment by utahaZZ** [comment]
Can you tell me where to change the font?

**Comment by utahaZZ** [comment]
thanks for your support :)

**Comment by bcarrier** [comment]
Please let us know which font you use.
