### ISSUE TITLE
Backend Endpoints

### ISSUE THREAD

**Issue by xQsme** [sleuthkit/autopsy#5151]
Hi, sorry to be writing an issue about this, but I've looked through the source code and was unable to understand if there are backend endpoints capable of communicating with a web front end I plan on developing.
My goal is to recreate the UI in web page form, so that Autopsy can be used in a cross platform environment successfully.
Any tips are appreciated, thanks

**Comment by rcordovano** [comment]
There are currently no back end endpoints to support a web front end. We are actually working on creating the first of these and are thinking a great deal about developing a web front end. @bcarrier may have more to say on this topic.
