### ISSUE TITLE
4.12.0 Linux Installation

### ISSUE THREAD

**Issue by d0n601** [sleuthkit/autopsy#5324]
Download page https://www.autopsy.com/download/, contains broken link to sleuthkit dependency. 

This link 404's

https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.6.7/sleuthkit-java_4.6.7-1_amd64.deb

Seems like the only option for Linux users is to install 4.11.0 instead.

**Comment by esaunders** [comment]
4.13.0 has recently been released and the sleuthkit java package can be found at https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.7.0/sleuthkit-java_4.7.0-1_amd64.deb
