### ISSUE TITLE
Add Data Source does nothing in GUI - Windows Installation

### ISSUE THREAD

**Issue by jknyght9** [sleuthkit/autopsy#5343]
Recently updated to 4.13.0, created a new case, and tried to Add Data Source. The orange status circle comes up, then goes away without doing anything. I even tried going to Case > Add Data Source, but it gets stuck and nothing happens.

**Comment by TroySchnack** [comment]
Had the same issue. Had to delete %AppData%\autopsy folder to clear old settings, Python modules etc. Re-installed modules and it now works fine.

**Comment by jknyght9** [comment]
Yep, right after I submitted this, I cleared everything out, uninstalled, and reinstalled. Everything works now. Thank you.
