### ISSUE TITLE
Autopsy not working with OpenJDK on Linux

### ISSUE THREAD

**Issue by mfrade** [sleuthkit/autopsy#5359]
The news.txt file states:
> Switch from Oracle JDK to **OpenJDK** 1.8.

which is great news, but unfortunately Autopsy gives the following warning messages on Linux:
`$ ./autopsy` 
`WARNING: An illegal reflective access operation has occurred`
`WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/mfrade/autopsy-4.13.0/platform/lib/boot.jar) to field java.net.URL.handler`
`WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory`
`WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations`
`WARNING: All illegal access operations will be denied in a future release`

and then the GUI shows an error message about not being able to load the modules.

However, if I change back to **Oracle Java** 1.8 Autopsy starts without any problem.
It seems that there are some dependencies to solve from Oracle Java...

**Comment by esaunders** [comment]
Can you please send along your messages.log file which is typically found under ~/.autopsy/dev/var/log.
Thanks.

**Comment by mfrade** [comment]
> Any Java 8 version of OpenJDK/OpenJFX distribution should suffice.

So, I've used the OpenJDK 1.8 that is available on the Ubuntu 18.04 repositories and downgraded JavaFX to the 1.8 version:
```
sudo apt purge openjfx
sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
sudo apt-mark hold openjfx libopenjfx-jni libopenjfx-java
```

I've attached 2 versions of the message.log file, one with OpenJDK and other with OracleDK.

[messages.log--OpenJDK.txt](https://github.com/sleuthkit/autopsy/files/3756889/messages.log--OpenJDK.txt)
[messages.log--OracleJDK.txt](https://github.com/sleuthkit/autopsy/files/3756890/messages.log--OracleJDK.txt)

**Comment by mfrade** [comment]
I carefully followed the new instructions on the Running_Linux_OSX.txt file, but Autopsy still doesn't run, but this time the behavior is different: it shows a "NetBeans Platform 8.2" window. 

Here's the steps I performed: 
```
$ sudo apt install ./zulu8.42.0.21-ca-jre8.0.232-linux_amd64.deb
$ sudo tar -xvzf zulu8.40.0.25-ca-fx-jre8.0.222-linux_x64.tar.gz --strip-components=1

$ sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/zre-8-amd64/bin/java                1084200   auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
* 3            /usr/lib/jvm/zre-8-amd64/bin/java                1084200   manual mode

Press <enter> to keep the current choice[*], or type selection number: 3

# reboot

$ echo $JAVA_HOME
/usr/lib/jvm/zre-8-amd64

$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-linux64) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-linux64) (build 25.222-b10, mixed mode)
```
However, when I run `./autopsy` I see a "NetBeans Platform 8.2" window instead of the regular Autopsy window. When I click on help -> about it shows:
```
Product Version: NetBeans Platform 8.2 (Build 201609300101)
Java: 11.0.4; OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu218.04.3
Runtime: OpenJDK Runtime Environment 11.0.4+11-post-Ubuntu-1ubuntu218.04.3
System: Linux version 5.0.0-32-generic running on amd64; UTF-8; en_US
User directory: /home/mfrade/autopsy-4.13.0/bin
Cache directory: /var/cache
```
The `message.log` file is not updated and for some odd reason it still shows OpenJDK 11.

**Comment by esaunders** [comment]
Do you have NetBeans installed?

**Comment by esaunders** [comment]
Also, for the step where you extracted the contents of JavaFX were you in the /usr/lib/jvm/zre-8-amd64 (i.e. JAVA_HOME) directory? The example from the Running_Linux_OSX.txt file explicitly extracts the contents to that folder as follows:

sudo tar xzf ~/Downloads/zulu8.40.0.25-ca-fx-jre8.0.222-linux_x64.tar.gz -C /usr/lib/jvm/zre-8-amd64 --strip-components=1

**Comment by mfrade** [comment]
No, I don't have NetBeans installed.

**Comment by mfrade** [comment]
Problem solved.
I had inserted an "echo $JAVA_HOME" inside the bin/autopsy script to make sure it was using the right java version. For some odd reason that line interfered with the start of autopsy. Deleted that line and now it's working. Thank you for the help.

**Comment by esaunders** [comment]
Good to know. Thanks.

**Comment by WesR** [comment]
Wanted to chime in, I'm also based on ubuntu 18, and have both openjdk 11 and 8 installed. I have my path set correctly ($JAVA_HOME), autopsy would launch with the same error:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/myusername/Documents/for/autopsy-4.13.0/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I checked the logs and saw it was trying to load java 11:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/wes/Documents/FTK/autopsy-4.13.0/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
It was also visible in the UI that it was using java 11. I removed java 11, but it still tried to reference it. I ultimately solved it by hard coding the path in the launch script.

```
       if [ -x /bin/bash ]
       then
           sh=/bin/bash
       fi
       eval exec $sh '"$nbexec"' \
            --jdkhome '"/usr/lib/jvm/java-8-openjdk-amd64/"' \
            --clusters '"$clusters"' \
            --userdir '"${userdir}"' \
            ${default_options} \
            "$args"
       exit 1
        ;;
```
