### ISSUE TITLE
Add Data Source - Memory Image

### ISSUE THREAD

**Issue by jknyght9** [sleuthkit/autopsy#5381]
According to the documentation under Volatility Output Module, I should have an option to import a memory image; however, I do not have this option. Can you help?

**Comment by markmckinnon** [comment]
You will need to enable plugin.  You can do this by going to the plugin option under the tools menu.  From there click on the "installed" tab and you will see the experimental plugin.  Enable the plugin and then you should then see a new type of data source to add called "Memory Image File (Volatility)".

**Comment by jknyght9** [comment]
That worked! Thank you.

**Comment by markmckinnon** [comment]
Glad it worked.  Can you please close this issue when you get a chance.  Thanks.
