### ISSUE TITLE
core jarfile java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by tellauri** [sleuthkit/autopsy#5504]
Hello i've this error on startup

org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: C:\Users\Public\***\autopsy\autopsy-4.13.0\autopsy\modules\org-sleuthkit-autopsy-core.jar: java.lang.ExceptionInInitializerError

windows 10
autopsy-4.13.0
java version "1.8.0_231"

**Comment by esaunders** [comment]
Can you send along your messages.log file? You should be able to find it in %APPDATA%\autopsy\var\log.

**Comment by tellauri** [comment]
[messages.log](https://github.com/sleuthkit/autopsy/files/3977205/messages.log)

**Comment by esaunders** [comment]
Interesting...it looks like your roaming profile is configured to be on a network share and the following message appears in the log file:
`INFO [org.netbeans.core.startup.ModuleList]
java.io.IOException: Couldn't get lock for \\server\home$\user\AppdataRoaming\.autopsy\dev\var\log\autopsy.log, maxLocks: 100`

Do you have an autopsy.log file in that location and if so can you also send it along?

If the network share is causing the problem you might be able to work around it by (a) creating an alternate location for the autopsy user directory (e.g. C:\Users\user\autopsy_userdir) and (b) running Autopsy from the command line as follows: 'autopsy64.exe --userdir C:\Users\user\autopsy_userdir' (or the path to whichever directory you created).

Let us know how it goes.

**Comment by tellauri** [comment]
The --userdir switch works like a charm ! Thank you very much !
