### ISSUE TITLE
Autopsy 4.13.0 - ImportError: No module named blackboardutils

### ISSUE THREAD

**Issue by slo-sleuth** [sleuthkit/autopsy#5527]
I receive the following error when starting a new case under Mac OS 10.13.6:

> SEVERE: Failed to load AndroidModuleFactory from /Users/user/Downloads/autopsy-4.13.0/autopsy/InternalPythonModules/android/module.py
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/user/Downloads/autopsy-4.13.0/autopsy/InternalPythonModules/android/module.py", line 49, in <module>
>     import imo
>   File "/Users/user/Downloads/autopsy-4.13.0/autopsy/InternalPythonModules/android/imo.py", line 46, in <module>
>     from org.sleuthkit.datamodel.blackboardutils import CommunicationArtifactsHelper
> ImportError: No module named blackboardutils
>

**Comment by slo-sleuth** [comment]
Reviewing past issue #5351 I checked the Sleuthkit 4.7.0 package and found the blackboard directory.

I rebuilt Sleuthkit successfully:

> Buildfile: /Users/jlehr/Downloads/sleuthkit-4.7.0/bindings/java/build.xml
>
> 
> 
> testTSKLibs:
> 
> check-native-build-mac:
> 
> check-native-build-unix:
> 
> check-native-build:
> 
> check-build:
> 
> dist:
> 
> 
>
> BUILD SUCCESSFUL
> Total time: 0 seconds
> make[3]: Nothing to be done for `install-exec-am'.
>  /usr/local/bin/gmkdir -p '/usr/local/share/java'
>  /usr/local/bin/ginstall -c -m 644 ../../bindings/java/dist/sleuthkit-4.7.0.jar '/usr/local/share/java'
> make[2]: Nothing to be done for `install-exec-am'.
>  /usr/local/bin/gmkdir -p '/usr/local/share'
>  /usr/local/bin/gmkdir -p '/usr/local/share/tsk/sorter'
>  /usr/local/bin/ginstall -c -m 644  tsk/sorter/default.sort tsk/sorter/freebsd.sort tsk/sorter/images.sort tsk/sorter/linux.sort tsk/sorter/openbsd.sort tsk/sorter/solaris.sort tsk/sorter/windows.sort '/usr/local/share/tsk/sorter'
>  /usr/local/bin/gmkdir -p '/usr/local/include'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/base'
>  /usr/local/bin/ginstall -c -m 644  tsk/base/tsk_base.h tsk/base/tsk_os.h '/usr/local/include/tsk/base'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/vs'
>  /usr/local/bin/ginstall -c -m 644  tsk/vs/tsk_vs.h tsk/vs/tsk_bsd.h tsk/vs/tsk_dos.h tsk/vs/tsk_gpt.h tsk/vs/tsk_mac.h tsk/vs/tsk_sun.h '/usr/local/include/tsk/vs'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/fs'
>  /usr/local/bin/ginstall -c -m 644  tsk/fs/tsk_fs.h tsk/fs/tsk_ffs.h tsk/fs/tsk_ext2fs.h tsk/fs/tsk_fatfs.h tsk/fs/tsk_ntfs.h tsk/fs/tsk_iso9660.h tsk/fs/tsk_hfs.h tsk/fs/tsk_yaffs.h tsk/fs/tsk_exfatfs.h tsk/fs/tsk_fatxxfs.h '/usr/local/include/tsk/fs'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/img'
>  /usr/local/bin/ginstall -c -m 644  tsk/img/tsk_img.h '/usr/local/include/tsk/img'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/auto'
>  /usr/local/bin/ginstall -c -m 644  tsk/auto/tsk_auto.h tsk/auto/tsk_is_image_supported.h '/usr/local/include/tsk/auto'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk/hashdb'
>  /usr/local/bin/ginstall -c -m 644  tsk/hashdb/tsk_hashdb.h '/usr/local/include/tsk/hashdb'
>  /usr/local/bin/gmkdir -p '/usr/local/include/tsk'
>  /usr/local/bin/ginstall -c -m 644  tsk/libtsk.h tsk/tsk_incs.h '/usr/local/include/tsk'

The same error occurs when creating a new case: The AndroidFactorModule fails to load because the blackboardutils module is not found.

**Comment by rcordovano** [comment]
Yes, the following line was missing from makefile.am:

bindings/java/src/org/sleuthkit/datamodel/blackboardutils/*.java \

as noted in #5351. The source code in the release-4.7.0 branch has been updated, but I now realize that this was not propagated to the master branch. It also was not retrofitted into the assets at https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.7.0. Getting the fi into the assets falls to @bcarrier. However, the fix **is** in the release-4.8.0 and develop branches. Release 4.8.0 will happen soon.

**Comment by slo-sleuth** [comment]
Great, thank you. I saw in the previous issue that there was a change needed in the make file but not the details of the change. I’ll patch or upgrade and close the issue when verified (though it’s certainly the same problem).

**Comment by slo-sleuth** [comment]
I downloaded the latest Makefile.am.  It has the patch:

> $ grep blackboard Makefile.am 
>     bindings/java/src/org/sleuthkit/datamodel/blackboardutils/*.java \

However, the import error for blackboardutils still occurs.  No errors on sleuthkit 4.7.0 build.

**Comment by slo-sleuth** [comment]
I patched the Makefile.am, downloaded the /blackboardutils folder source files and rebuilt.  Same problem.  

I downloaded the latest source for 4.8.0 and built it, same problem.
