### ISSUE TITLE
Failure to open a case from 4.9.1 in 4.13.0

### ISSUE THREAD

**Issue by beyefendi** [sleuthkit/autopsy#5562]
I have a case generated in version 4.9.1.
Version 4.13.0 fails to open this case.
The log file in .autops/var/log is attached.

[autopsy.log](https://github.com/sleuthkit/autopsy/files/4032712/autopsy.log)

**Comment by rcordovano** [comment]
@beyefendi, I'm sorry to say that we have become aware of some errors in the database schema update code for the 4.12.0 and 4.13.0 releases. I think this has come to roost on you. We have fixed the issues for the upcoming 4.14.0 release (before the end of the month) and improved our pre-release testing to avoid "shipping" such errors in the future. Do you have the backup copy of the autopsy.db file in your case directory?

**Comment by beyefendi** [comment]
@rcordovano, very good to hear to access previous case files. yes i have the db file, if it is valuable for you, i can share it privately.

**Comment by rcordovano** [comment]
@beyefendi, I'm glad to hear that you can use the backup case database to continue to look at the case in Autopsy 4.9.1, assuming it is still relevant.

At this point, if you are willing, I propose that you try again with the fixes that we have in the "any day now" 4.14.0 release. Two different developers have created cases with 4.9.1 and then opened them with our 4.14.0 release candidate.

**Comment by beyefendi** [comment]
I am waiting for the new release and to be one of the tester for this issue.
Then I will confirm it from here.

**Comment by beyefendi** [comment]
I confirm that version 4.14.0 successfully opens database file
