### ISSUE TITLE
Central 501 HTTPS Required 

### ISSUE THREAD

**Issue by xQsme** [sleuthkit/autopsy#5605]
https://support.sonatype.com/hc/en-us/articles/360041287334

The workaround for now would be to add the https url to the ivysettings.xml files such as:
`<ibiblio name="central" m2compatible="true" root="https://repo1.maven.org/maven2"/>`

Same thing for java bindings on the sleuth kit
Also I downloaded ivy jar directly, not sure what the workaround for that one would be

**Comment by esaunders** [comment]
This should be fixed by https://github.com/sleuthkit/autopsy/pull/5597
