### ISSUE TITLE
Cannot open any files

### ISSUE THREAD

**Issue by JX-CW** [sleuthkit/autopsy#5629]
I've completed the setup on Linux Mint 19.03, but when i launch /bin/autopsy the GUI loads, but without the prompt of new case or open case, so i cannot do anything. There is one error opening the file.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/chris183/autopsy-4.14.0/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by esaunders** [comment]
Can you provide the Autopsy log files which you should find in ~/.autopsy/dev/var/log?

**Comment by JX-CW** [comment]
Ok @esaunders ,  here they are : https://pastebin.com/wC86b1qT

**Comment by esaunders** [comment]
Your problem is that Java 11 is being used when Autopsy depends on Java 8.
See https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt for instructions on getting a Java 8 distribution that will work.

>   Java; VM; Vendor        = 11.0.5; OpenJDK 64-Bit Server VM 11.0.5+10-post-Ubuntu-0ubuntu1.118.04; Private Build
  Runtime                 = OpenJDK Runtime Environment 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
  Java Home               = /usr/lib/jvm/java-11-openjdk-amd64

**Comment by JX-CW** [comment]
Well, i tried that, re-ran unix_setup.sh, and the error is gone, but there is still no pop-up to open new case etc. help :(

Log file: 
https://www.mediafire.com/file/hnmmt4g80xest7w/messages.log.1/file

**Comment by JX-CW** [comment]
Nevermind, I found out that somehow module autopsy-core or something like that was not activated. Activating it in the plugins menu and restarting has fixed my problem.
