### ISSUE TITLE
Previously loaded “module name” could not be found

### ISSUE THREAD

**Issue by europa9** [sleuthkit/autopsy#5660]
Im developing modules for Autopsy.
When I run Tools->Run ingest modules I get the message:
Previously loaded “module name” could not be found

How can I remove this error message?
The error message comes everytime I go to Run ingest modules, even after restarting Autopsy. 

![Image of Yaktocat](https://aws1.discourse-cdn.com/free1/uploads/sleuthkit/original/1X/83e6cc0bc4e7f6f7945b850654a6cfc0a2c19fa5.png)

My OS: Windows 10
Autopsy version: 4.14.0
Python module: https://github.com/europa9/AutopsyPlugins/blob/master/ExportAllImagesVideoesAudio/exportAllImagesVideoesAudio.py

**Comment by markmckinnon** [comment]
Go to the following
directory C:\Users\<username>\AppData\Roaming\autopsy\config\IngestModuleSettings\org.sleuthkit.autopsy.casemodule.AddImageWizardIngestConfigPanel

Find your module should start with org.python.proxies.module name and
delete this file.  You can actually delete all the files as well if you
want to these are the settings for each module.

You may also have a few other directories under here
C:\Users\<username>\AppData\Roaming\autopsy\config\IngestModuleSettings\
you can look in those directories to see if your module settings are there
as well and delete them.

Next time you run your ingest modules they will get recreated.

**Comment by esaunders** [comment]
@europa9 Can this issue be closed out now that you've removed the comma from your module name?

**Comment by europa9** [comment]
Yes, the case can ble closed. 
The fault was that I had comma in the module name,
