### ISSUE TITLE
Improve Linux install instructions

### ISSUE THREAD

**Issue by mfrade** [sleuthkit/autopsy#5734]
The file [Running_Linux_OSX.txt](https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt)
states that in order to guarantee the installation of JavaFX we should install an outdated version of Java:
`sudo apt-get install bellsoft-java8=1.8.0.232+10`

However, I beleive there's a better solution, accordinglinly to [Bell Liberica](https://bell-sw.com/pages/repositories#apt-repository-deb-based-linux-distributions):

> All our packages follow the naming conventions described below
> `bellsoft-java<VNUM>-<VARIANT>`
> where
> `VNUM` is a version number most known as a feature version or formerly known as a major version.
>`VARIANT` defines the content of the package. Liberica is distributed in the following variants of packages:
>
> `<no suffix>` — a regular package that contains the full Liberica JDK, **not including JavaFX**.
>`full` — contains the full Liberica JDK, **including JavaFX** and a variety of JVMs for platforms that support it.
>`runtime-full` — contains Java SE Runtime Environment, **including JavaFX**.

So, `bellsoft-java8` doesn't include JavaFX, but both `bellsoft-java8-full` and `bellsoft-java8-runtime-full` include JavaFX. Rightnow I'm running Autopsy 4.14 without any problems on Ubuntu 18.04 with `bellsoft-java8-full` and Java build `1.8.0_242-b07`.

Personaly I think that installing an outdated version of Java is not the best option and therefore I suggest to update the Linux install instructions with:
`sudo apt-get install bellsoft-java8-full`

**Comment by esaunders** [comment]
@mfrade Thanks for the suggestion. This change has now been merged. Can you close out this issue if you are satisfied with the change?

**Comment by mfrade** [comment]
@esaunders I'm completely satisfied with the change. Issue closed.

**Comment by webhat** [comment]
I would like to add that the version that is provided with the current Autopsy Training still contains this issue.
