### ISSUE TITLE
Portable case with Autopsy binaries

### ISSUE THREAD

**Issue by jupie** [sleuthkit/autopsy#5774]
I like your generating Portable case feature. Is it possible to add an Option which copies the binaries of autopsy to the Portablecase and add a commandlineoption to specify a Case. 

The Idea is to make one click to the portable case and open it without any isntallation. 

I think this is a little Feature request because there is a similar option called  "make live Triage"

**Comment by bcarrier** [comment]
Are you imagining something like:
- Autopsy makes a folder with 2 subfolders:
-- The case folder
-- The autopsy program folder
- The root of new folder has a file named something like "opencase.bat" and that would launch Autopsy and automatically open the portable case?

**Comment by jupie** [comment]
Exactly :)

**Comment by markmckinnon** [comment]
This feature is available in 4.19.X of Autopsy.  Closing this issue as complete.
