### ISSUE TITLE
Feature Request: Include Dates from Logical File Data Sources

### ISSUE THREAD

**Issue by slo-sleuth** [sleuthkit/autopsy#5852]
Autopsy does not add MACB times from logical file data sources.  However, analysis can be aided legally restricted to data _created_ during specific time frames.  

While date stamps can be confusing/misleading in from logical sources, it should be up to the examiner to determine the validity and meaning of available time stamps.  They should not be excluded by default, or at the very least, should optional.

**Comment by markmckinnon** [comment]
Addressed in Release 4.21.0 of Autopsy.  If there are any questions/issue please create a new issue or reopen this one.
