### ISSUE TITLE
[Autopsy 4.15.0] "Add Data Source > Memory Image File" option missing in GUI

### ISSUE THREAD

**Issue by Baricanac** [sleuthkit/autopsy#5892]
I wanted to add a ".mem" file type as a new data source to my existing case, but I then noticed the "Memory Image File" option is missing?

![01](https://user-images.githubusercontent.com/43236274/81746781-52ee0000-94a7-11ea-896e-be8988b2cb6a.PNG)

http://sleuthkit.org/autopsy/docs/user-docs/4.15.0/volatility_dsp_select.png

**Comment by rcordovano** [comment]
Autopsy does not support processing of memory image files yet.

**Comment by Baricanac** [comment]
> Autopsy does not support processing of memory image files yet.

http://sleuthkit.org/autopsy/docs/user-docs/4.15.0/volatility_dsp_page.html

**Comment by Baricanac** [comment]
> Have you enabled the experimental module? http://sleuthkit.org/autopsy/docs/user-docs/4.15.0/experimental_page.html

I must have forgotten to enable
