### ISSUE TITLE
Can't open log: autopsy.log at /usr/share/autopsy/lib/Print.pm line 383.

### ISSUE THREAD

**Issue by khalidalwalid** [sleuthkit/autopsy#6126]
Hello, I wanna ask for your help guys about this issue..

When I run autopsy, it says "Can't open log: autopsy.log at /usr/share/autopsy/lib/Print.pm line 383."
![autopsy issue](https://user-images.githubusercontent.com/33023197/88263830-adba8980-cc98-11ea-9755-ad98fb14627b.png)

and even I run the localhost server, it doesn't work..
![error connection](https://user-images.githubusercontent.com/33023197/88263882-caef5800-cc98-11ea-8e8b-16595b4a2fb8.png)

**Comment by khalidalwalid** [comment]
what should I do to fix this problem?

**Comment by esaunders** [comment]
Autopsy 2 is obsolete (the last update was in 2010!). I don't know why it continues to be part of the Kali distribution.
If you want to try the latest version of Autopsy you can find it here: https://github.com/sleuthkit/autopsy/releases/tag/autopsy-4.15.0

**Comment by khalidalwalid** [comment]
thanks for your suggestion, dude!
I'll try the new one.

**Comment by EnricoHuber** [comment]
I've solved the problem running Autopsy as root.


sudo autopsy

**Comment by Optane002** [comment]
Open a New Terminal and type
 **sudo autopsy**

**Comment by jamesngangabest** [comment]
you should run it as root , that simple (sudo su)
then 
autopsy
