### ISSUE TITLE
Multi user client issues

### ISSUE THREAD

**Issue by zorovj** [sleuthkit/autopsy#6321]
Hello,
I have setup a Remote Windows server with Postgres and Solr as per the latest documentation. But when I try to test connection from the autopsy client on a Windows system, I get an "**invalid port**" error.

The ports are open and a Tcp connection can be established from the client system.

The error logs for solr service test shows that the server resets connection after a TCP handshake.
whereas for Postgres it shows - "**Failed to acquire ephemeral connection to postgresql**"

Any idea, what could be the issue?

Thanks!

**Comment by esaunders** [comment]
Looking at the code suggests that there should be more information to go along with that "Failed to acquire ephemeral connection..." message. It should be followed by the exact exception that happened. Check the messages.log and autopsy.log files in %APPDATA%\autopsy\var\log.
You might also want to take a look at the logs on the PostgreSQL server to see if connection attempts are getting through. Those logs are usually in the data/pg_log folder.

**Comment by zorovj** [comment]
messages.log show this for failed solr connection:

WARNING [org.netbeans.core.TimableEventQueue]: too much time in AWT thread org.netbeans.modules.sampler.InternalSampler@38f22d79

91119737 [AWT-EventQueue-0] INFO org.apache.http.impl.client.SystemDefaultHttpClient - I/O exception (java.net.SocketException) caught when processing request to {}->http://redacted.domain:8983: Connection reset
91119738 [AWT-EventQueue-0] INFO org.apache.http.impl.client.SystemDefaultHttpClient - Retrying request to {}->http://redacted.domain:8983

**Comment by zorovj** [comment]
it was actually a firewall rule blocking the connection. issue resolved now
