### ISSUE TITLE
How do I get started with this Autopsy tool ?

### ISSUE THREAD

**Issue by ankitgogri** [sleuthkit/autopsy#6388]
I am very new in this area and need your suggestion on getting started with this tool. Any thoughts suggestions appreciated thanks. -Ankit

**Comment by APriestman** [comment]
Read the documentation here: http://sleuthkit.org/autopsy/docs/user-docs/4.17.0/

If you still have questions, our discourse group is a good place to ask them. 
https://sleuthkit.discourse.group/

**Comment by markmckinnon** [comment]
Closing as answered.  If you need to you can reopen this issue.
