### ISSUE TITLE
Failed to open remote events channel error (Multi user setup)

### ISSUE THREAD

**Issue by zorovj** [sleuthkit/autopsy#6396]
Hello,
While creating a new case in a multi user setup I get the above error and the case creation fails. Firewall rules are correct and no AV is blocking it. Please suggest any possible solutions.

autopsy.log shows the following:

Failed to open remote event channel.
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: org.sleuthkit.autopsy.casemodule.CaseActionException: Failed to open remote events channel:
Failed to open remote event channel.
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
org.sleuthkit.autopsy.casemodule.CaseActionException: Failed to open remote events channel:
Failed to open remote event channel.
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
org.sleuthkit.autopsy.events.AutopsyEventException: Failed to open remote event channel
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
javax.jms.JMSException: Could not connect to broker URL: tcp://redacted.com:61616?wireFormat.maxInactivityDuration=0. Reason: java.net.ConnectException: Connection timed out: connect
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
java.net.ConnectException: Connection timed out: connect
	org.sleuthkit.autopsy.casemodule.Case.doOpenCaseAction(Case.java:1923)
	org.sleuthkit.autopsy.casemodule.Case.openAsCurrentCase(Case.java:885)
	org.sleuthkit.autopsy.casemodule.Case.createAsCurrentCase(Case.java:615)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:91)
	org.sleuthkit.autopsy.casemodule.NewCaseWizardAction$1.doInBackground(NewCaseWizardAction.java:79)
	javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	javax.swing.SwingWorker.run(SwingWorker.java:334)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)

**Comment by zorovj** [comment]
On the solr instance the error log shows:

org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Cannot create directory:  F:\ModuleOutput\keywordsearch\data\solr4_schema2.2\index

The user with which solr runs has full permissions to the share drive F:\. What could be the issue?

**Comment by rcordovano** [comment]
The error message about failing to open the remote event channel indicates that there was a problem making the connection to the ActiveMQ Message Broker that is used to pass application events between cluster nodes that have a given case open. The relevant part of the stack traces is this:

javax.jms.JMSException: Could not connect to broker URL: tcp://redacted.com:61616?wireFormat.maxInactivityDuration=0. Reason: java.net.ConnectException: Connection timed out: connect

Have you configured an ActiveMQ Message Broker as described here: http://sleuthkit.org/autopsy/docs/user-docs/4.17.0/install_activemq_page.html?

**Comment by zorovj** [comment]
the connection of ActiveMQ was unstable due to the dynamic port. changing the port below the dynamic port range works fine.
Thanks for the help @rcordovano
