### ISSUE TITLE
4.16 - No "OPTIONS" Menu under the Tools.. 

### ISSUE THREAD

**Issue by rjpear** [sleuthkit/autopsy#6437]
Hi Folks,  Under Windows 10 (64)..  v.4.16 is not displaying the "Options" menu item (Where we can select HASH sets etc.).  In fact  I installed 4.14 and it does the same thing.   In fact the "PLUG IN" option has no TEXT (looks BLANK) but I can select it.  
![Autopsy Tools](https://user-images.githubusercontent.com/61298263/98176651-f2280900-1ec6-11eb-8d37-97e815cb1318.JPG)
  I have attached the screen shot.    Thanks...

**Comment by APriestman** [comment]
Try deleting the Autopsy user folder (see http://sleuthkit.org/autopsy/docs/user-docs/4.17.0/troubleshooting_page.html) and see if the options menu comes back. I believe we've seen third party modules cause this issue - did you have any installed?

**Comment by rjpear** [comment]
Bingo! ..Worked like a champ!.   I did have (I installed all of them from a
ZIP on Github) most, if not all of them.  I installed them all at once.  So
I cannot narrow it down to a particular one at this point.  But that did
fix it.. Thanks!

**Comment by APriestman** [comment]
We've seen issues with ForensicExpertWitnessReport, so if you installed that try omitting it this time.
