### ISSUE TITLE
Integer attributes sort as strings

### ISSUE THREAD

**Issue by L-Andrade** [sleuthkit/autopsy#6458]
Hello,

When an artifact is added to the blackboard and it has an attribute of type Integer (`BlackboardAttribute.TSK_BLACKBOARD_ATTRIBUTE_VALUE_TYPE.INTEGER`), tapping the column to sort it still sorts the column as if the attribute was a string (e.g. `10 -> 10000 -> 30` instead of `10 -> 30 -> 10000 `).

Is it necessary to do something else other than use the proper attribute type, or is it a bug?

Edit: I tested in Autopsy 4.15.0 and 4.17.0, and the result was the same.

Edit2: Image for more context:
![image](https://user-images.githubusercontent.com/20290474/98997181-048bed80-252c-11eb-9dd5-e252697c94d5.png)

Thanks in advance.

**Comment by rcordovano** [comment]
This is a bug. Many attributes get loaded in BlackboardArtifactNode (artifact "model" class for tabular results views) by the following line of code (Line 985c of BlackboardArtifactNode.java) which converts the attribute value to a string:

`map.put(attribute.getAttributeType().getDisplayName(), attribute.getDisplayString());`

I will add this issue to our internal bug tracking system here at Basis Technology. Hopefully, we will be able to address it for the Autopsy 4.18.0 release scheduled for January.

**Comment by rcordovano** [comment]
@L-Andrade, the bug will definitely be fixed in the Autopsy 4.18.0 release scheduled for January (https://github.com/sleuthkit/autopsy/pull/6490).
