### ISSUE TITLE
Autopsy 4.17 on linux

### ISSUE THREAD

**Issue by TheMMcOfficial** [sleuthkit/autopsy#6507]
Kernel 5.9

I did the installation following those instructions: https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt

```
wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add -
echo "deb [arch=amd64] https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
sudo apt update
sudo apt install -y bellsoft-java8-full
export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64
wget https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.10.1/sleuthkit-java_4.10.1-1_amd64.deb
sudo apt install -y ./sleuthkit-java_4.10.1-1_amd64.deb
wget https://github.com/sleuthkit/autopsy/releases/download/autopsy-4.17.0/autopsy-4.17.0.zip
unzip autopsy-4.17.0.zip
cd autopsy-4.17.0
chmod +x unix_setup.sh
sh unix_setup.sh
```

after the installation done I run Autospy and I get this error when I try to activate some plugins. I can't create a case...

`Activation failed: StandardModule:org.sleuthkit.autopsy.core jarFile: /opt/autopsy-4.17.0/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.UnsupportedClassVersionError: org/sleuthkit/datamodel/SleuthkitJNI has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by markmckinnon** [comment]
Can check the md5 hash for the sleuth kit Deb file. It should have a md5 hash of c3ca85a89ba19ed34f26d227384a4f11. If not then you have an incorrect file and need to refine load the Deb file and install it.

**Comment by rcordovano** [comment]
@TheMMcOfficial, the error definitely indicates that you have the erroneous Debian package. Please download the corrected package and try again.

**Comment by TheMMcOfficial** [comment]
```
❯ md5sum sleuthkit-java_4.10.1-1_amd64.deb
c3ca85a89ba19ed34f26d227384a4f11  sleuthkit-java_4.10.1-1_amd64.deb
```

**Comment by esaunders** [comment]
As @rcordovano  mentioned above, the error message almost certainly is an indication that the installed Sleuthkit Java bindings are not the right ones. Try uninstalling sleuthkit-java using 'sudo apt remove sleuthkit-java' and reinstall using 'sudo apt install ./sleuthkit-java_4.10.1-1_amd64.deb'

**Comment by TheMMcOfficial** [comment]
I did it nothing changed. I just realise it works when I use Autopsy on root but with my normal user it doesn't works.

**Comment by esaunders** [comment]
Your "normal" user account must be picking up the TSK Java bindings from someplace else.
What does the output of 'sh ./unix_setup.sh' look like for both user accounts?

**Comment by TheMMcOfficial** [comment]
I found it. I had to delete the ".autopsy" folder in my "home". after it Autopsy are launching like it should.
Before delete the folder I have also reinstall the "sleuthkit-java_4.10.1-1_amd64.deb" and rerun the "unix_setup.sh". After it run like a charm.
