### ISSUE TITLE
Autopsy 4.17.0 crashes on Windows 10

### ISSUE THREAD

**Issue by atlantsecurity** [sleuthkit/autopsy#6616]
Error log is attached. 

At first I fixed it by reinstalling Java - then, after a reboot, reinstalling Java no longer helps, it still crashes every single time on startup. 

[hs_err_pid9868.log](https://github.com/sleuthkit/autopsy/files/5794842/hs_err_pid9868.log)

Same issue is reported by others here:
https://sleuthkit.discourse.group/t/autopsy-4-17-fatal-error-java-runtime/2349
and https://sleuthkit.discourse.group/t/autopsy-is-no-opening/2357

**Comment by markmckinnon** [comment]
Does upgrading to a newer release of Autopsy fix this issue?

**Comment by atlantsecurity** [comment]
Yes

**Comment by markmckinnon** [comment]
Closing the issue as resolved then.
