### ISSUE TITLE
ImageMagick setup

### ISSUE THREAD

**Issue by huddledfiber** [sleuthkit/autopsy#6709]
Running Linux Mint 20 (kernel 5.4.0-65).  I tried adding the deb-src numerous times and the command returns without error.  However when I check the sources.list file it isn't in there?  Copied and pasted the command to avoid syntax errors.

Separate issue I thought I'd mention if possible.  Followed the rest of the instructions and they all completed without error but the autopsy file isn't in /bin.  Going to try going through the instructions one more time and see if I missed anything.

Thanks.

**Comment by huddledfiber** [comment]
More info on the 2nd issue will create new issue to address it.

**Comment by markmckinnon** [comment]
ImageMagick has been replace in Autopsy 4.20 with libheif v1.12.0.  This should fix the issue you are having by upgrading to Autopsy 4.20.
