### ISSUE TITLE
CSV Export missing fields, header names

### ISSUE THREAD

**Issue by TroySchnack** [sleuthkit/autopsy#6717]
When exporting table or selected rows to CSV, fields and header names are missing and cause viewing issues with Excel, TimelineExplorer and others.

Autopsy 4.17.0 (RELEASE, Win10 x64 20H2, Installed from EXE

Export from Run Programs extended content view from SYSTEM & SRUDB. CSV file attached for review. All fields displayed properly in Autopsy program but export is missing data or blank columns.
[Run Programs 2021029112617.zip](https://github.com/sleuthkit/autopsy/files/5953111/Run.Programs.2021029112617.zip)

**Comment by miguel-negrao** [comment]
I have the same issue with Autopsy 4.20 when exporting the "Metadata" table. Columns are mis-aligned, and column headers are wrong. Example of  CSV generated (here in table form):


Source Name | Date Modified | Program Name | Last Printed Date | Date Created | User ID | Owner | Data Source
-- | -- | -- | -- | -- | -- | -- | --
b.docx | 2019-06-30 16:59:00 WEST | Microsoft Office Word | 2019-06-26 16:42:00 WEST | John Doe| John Doe | SSD01.E01 |  
a.pdf | 1.7 | 2019-07-01 22:15:21 WEST | 2019-07-01 22:15:21 WEST | John Doe| SSD01.E01 |   |  

This is a crucial functionality of Autopsy, without this working it is difficult to use the software...

**Comment by markmckinnon** [comment]
This should be in the next release of Autopsy
