### ISSUE TITLE
Keyword Search - IP Addresses 

### ISSUE THREAD

**Issue by tinchourteaga** [sleuthkit/autopsy#7104]
Hello,

Recently I've been using Autopsy to extract IP addresses from .evtx files using the Keyword Search module with Autopsy's default regular expression. However, some of the IP addresses seem to be incomplete, missing digits at the beginning or at the end of the IP, resulting in non-existent addresses or totally different ones. 

An example to clarify the issue:

![image](https://user-images.githubusercontent.com/38136900/124320021-84190c00-db51-11eb-8e3e-076346ec53b4.png)

I've tried adding different regex to retrieve IP but the output remains the same. It is worth mentioning that this issue happens only in some addresses, the vast majority of IP addresses are retrieved in the correct format.

If anybody knows a solution to this problem such as a better regular expression or even a plugin, it will be gladly welcomed and appreciated.

Thanks in advance,
Martín

**Comment by Seb2lyon** [comment]
Hello Martin,
I am very surprised about the 333 bytes of the first two IP addresses in your screenshot !!! 
However can you specify what were your regex ?

**Comment by tinchourteaga** [comment]
Hey Seb, don't mind the format of the IP addresses from the example. I just wrote random numbers. They are there just to exemplify how Autopsy is exporting the addresses (losing digits). 

The regex I'm using is Autopsy's default one: 
(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}(1[0-9]{2}|2[0-4][0-9]|25[0-5]|[1-9][0-9]|[0-9])

Here's a link to the code that contains the regex:
https://github.com/sleuthkit/autopsy/blob/343cc6e96041a2541418954a0b93fa47a96232ed/KeywordSearch/src/org/sleuthkit/autopsy/keywordsearch/KeywordSearchList.java#L49

**Comment by Seb2lyon** [comment]
Hi Martin.
My question about your examples (byte 333) was because the build-in regex search for bytes between 0 and 255... as it should be case with an IPv4 adress (so 333 was out of range). 
I tested the build-in regex on my own evtx files without any problem. Did you see in the indexted text if the missing digit's IPs are surrounded by some specific boundary characters ?

**Comment by tinchourteaga** [comment]
The answer to your question is: **yes**. The IPs have the minus sign (-) at the beginning and other numbers at the end.

For example:      -10.10.101.101xxxxx%%xxxx
(Where "x" is a number).

It's like Autopsy tries every combination... as it will export as IP addresses:
0.10.101.101
10.10.101.10
and then 10.10.101.101 (this would be the correct one)

__obs:_ doing some research I found that %%xxxx might be the ImpersonationLevel._

**Comment by Seb2lyon** [comment]
As you can see, Autopsy's build-in regex defined some boundary characters by default.
Do you try to create a keyword list with custom regex including the specific boundary characters you have noticed (if it's always the same pattern) ? 
Sorry but as I didn't meet the same problem than yours, I just try to find some way out.

**Comment by tinchourteaga** [comment]
Hi Seb, thank you for your time and help, but I will be moving to another tool that could do this without issues as I couldn't find a way to make this work.

Best regards.

**Comment by bcarrier** [comment]
@tinchourteaga So, to summarize, the ".333" number in the first example was made up and there isn't a bug about invalid IPs getting picked up.  T

he issue is the false positives and that Autopsy is bringing in subsets of the actual IP?  I.e. instead of just 11.22.33.44 it's also showing things like 1.22.33.44 and 11.22.33.4?

**Comment by tinchourteaga** [comment]
Hello bcarrier! 

Yes, that is exactly the issue. Having false positives is making my investigations difficult and I would hate switching tools, because Autopsy has been really helpful.
