### ISSUE TITLE
IP Addresses regex problem 

### ISSUE THREAD

**Issue by N-Sotelo98** [sleuthkit/autopsy#7191]
Hi there,

While using the keyword module searching for IP addresses, there seems to be a problem with the default regex expression since it doesn't identify the IP correctly . Here is an example:

![Captura](https://user-images.githubusercontent.com/35941294/128732038-e55dc234-f38c-4a2d-a151-49094be8cb97.JPG)

I've tried adding different regex to retrieve IP, but it didn't work

(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}

If anybody knows a solution to this problem I would really appreciate it.

Thanks in advance for your answers.

Regards.

**Comment by markmckinnon** [comment]
Can you try this regex instead and see what you come up with.  (25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}  the only difference from yours is the slash (\) before the period (.).  By adding the slash it does change the outcome of the query.

**Comment by N-Sotelo98** [comment]
Hi mark , thanks for answering

I have used your regex however it doesn't work properly with ip adrreses also it catches random numbers within the file (.evtx) 
 
![Captura](https://user-images.githubusercontent.com/35941294/130132570-43a52f67-40ab-4c81-a5ab-dadb47ea0283.JPG)

**Comment by markmckinnon** [comment]
What do you mean by random numbers within the file?   I just noticed what I copied over above did not have the \. in it, did you test with the \. in it?  I did notice that some of the things it will pull out are actual file names that have a version number in the file that looks like an IP address.

**Comment by N-Sotelo98** [comment]
Hey mark, 

The regex you suggested brings every number within the file. Tried using the . for the tests but  it is posible  I made a mistake.

(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])){3}
![WhatsApp Image 2021-08-24 at 10 54 58 AM](https://user-images.githubusercontent.com/35941294/130649514-5dee0253-37d2-4b4a-aff4-2a1b9e4d19d8.jpeg)
