### ISSUE TITLE
I cloned the source code in Linux 

### ISSUE THREAD

**Issue by ilich262** [sleuthkit/autopsy#7261]
Here is Autopsy github page :https://github.com/sleuthkit/autopsy Here is the releases page: https://github.com/sleuthkit/autopsy/releases

I cloned the source code in Linux but when I tried to run it, there was no bin folder. I had to download autopsy-4.19.1.zip in order to work. Why this program is different from other git hub repositories from which it's enough to clone source code? (In the releases page your can download the zip file that has the bin folder)

Please explain

**Comment by markmckinnon** [comment]
The source code is just that source,  It would need to be built in order to run.  The zip file that is in the releases is to be used for running the program in an environment if someone does not want to build from source.  Closing this as answered.  If you would like to reopen this issue you can.
