### ISSUE TITLE
Enhancement: "Add Data Source" for "Local files and folders" should support removing an individual entry

### ISSUE THREAD

**Issue by moshekaplan** [sleuthkit/autopsy#7347]
In the "Add Data Source" for "Local files and folders", instead of only having "Add" and "Clear", it should be possible to select an individual entry from the list of files and folders and remove it from the list

![image](https://user-images.githubusercontent.com/810279/137248739-34f365c3-cf46-4d66-9877-8e2c1398087c.png)

**Comment by markmckinnon** [comment]
This is referenced in PR https://github.com/sleuthkit/autopsy/pull/7705

**Comment by markmckinnon** [comment]
Addressed in Release 4.21.0 of Autopsy. If there are any questions/issue please create a new issue or reopen this one.
