### ISSUE TITLE
Library not found in jar (libtsk_jni)

### ISSUE THREAD

**Issue by fasssl** [sleuthkit/autopsy#7435]
Hi,
I have installed autopsy following the link https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt
is installed in Linux ubuntu

echo $JAVA_HOME
/usr/lib/jvm/bellsoft-java8-full-amd64

the autopsy logs shows:
  Java; VM; Vendor        = 1.8.0_312; OpenJDK 64-Bit Server VM 25.312-b07; BellSoft
  Java Home               = /usr/lib/jvm/bellsoft-java8-full-amd64/jre

the sleuthkit versión installed is:
  sleuthkit-java/now 4.8.0-1 amd64

when starting autopsy I get the error :
        Library not found in jar (libtsk_jni)
        SleuthkitJNI: failed to load libtsk_jni

I tried to install several versions of sleuthkit and remove the .autopsy 

can you give me any hint ?

thanks a lot
![autopsy](https://user-images.githubusercontent.com/14232621/143691078-7941f457-96df-481c-9b78-868a121b2085.png)

**Comment by markmckinnon** [comment]
It looks like you are trying to run Autopsy 4.19.2, for that you will need to install Sleuthkit 4.11.1 instead of 4.8.0

**Comment by fasssl** [comment]
thanks!

**Comment by bcarrier** [comment]
Here is the DEB file.

https://github.com/sleuthkit/sleuthkit/releases/download/sleuthkit-4.11.1/sleuthkit-java_4.11.1-1_amd64.deb
