### ISSUE TITLE
Autopsy adds numbers to filenames when extracting files

### ISSUE THREAD

**Issue by alphaGGG** [sleuthkit/autopsy#7549]
When right clicking on a file/directory and selecting "Extract file(s)" from the context menu, then selecting the target directory the resulting directory/file will have seemingly random numbers added to its name. e.g. "140100-.ssh" instead of ".ssh" .

Is this an intended behavior? It is very annoying, having to rename every file/directory.

Also Autopsy does not remember the last directory where extracted files were saved, instead reverts back to the default "Export" directory within the case.

v.4.19.3

**Comment by gdicristofaro** [comment]
Hi @alphaGGG ,

Here is a PR in review that should solve this problem: https://github.com/sleuthkit/autopsy/pull/7551

In this PR:
- Extracting a single file will prompt the user before overwriting a file.  No id will be prepended to the file name.
- Extracting a directory will prepend an id to child content only if a file of the same name already exists on disk.
- Extracting multiple files will prepend the id to all files.

**Comment by alphaGGG** [comment]
Why prepend an id to file/directory names without asking the user??? Thanks

**Comment by markmckinnon** [comment]
It is more efficient to prepend the id when selecting multiple files then trying to check if file exists every time so that you do not overwrite an existing file I. The directory.  If you want to extract multiple files in a directory then select the directory to extract then the directory will only have the is prepended.

**Comment by alphaGGG** [comment]
@bcarrier The new code will be a welcome change. Perhaps there could be a warning dialogue box displayed to explain what will happen or even allow the user to decide if they want the prepend to take place. Thanks.

**Comment by markmckinnon** [comment]
This has been added to the new version of Autopsy (4.20.0) that is now available.  Closing this as complete, if this is still an issue then you can reopen it.
