### ISSUE TITLE
Portable Case report string index out of range -1

### ISSUE THREAD

**Issue by rodhalverson** [sleuthkit/autopsy#7577]
Autopsy 4.19.3
Windows 10
Download install from autopsy.com/download 64bit
When generating a report type Portable Case I get the error.
Error generating report: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by APriestman** [comment]
Can you attach the full stack trace? See this page for how to access the logs: http://sleuthkit.org/autopsy/docs/user-docs/4.19.3/troubleshooting_page.html#troubleshooting_logs

**Comment by rodhalverson** [comment]
[autopsy.log.zip](https://github.com/sleuthkit/autopsy/files/8254692/autopsy.log.zip)

**Comment by APriestman** [comment]
The zip file appears invalid. Regardless, this is mostly likely a known bug that we've fixed for the next release (we were seeing the same error message).

**Comment by rodhalverson** [comment]
SEVERE: failed to generate reports
java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	java.util.concurrent.FutureTask.report(FutureTask.java:122)
	java.util.concurrent.FutureTask.get(FutureTask.java:192)
	javax.swing.SwingWorker.get(SwingWorker.java:602)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction$ReportWorker.done(ReportWizardAction.java:251)
	javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	javax.swing.Timer.fireActionPerformed(Timer.java:313)
	javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	java.awt.EventQueue.access$500(EventQueue.java:97)
	java.awt.EventQueue$3.run(EventQueue.java:709)
	java.awt.EventQueue$3.run(EventQueue.java:703)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	java.security.AccessController.doPrivileged(Native Method)
	java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	java.awt.Dialog.show(Dialog.java:1084)
	java.awt.Component.show(Component.java:1671)
	java.awt.Component.setVisible(Component.java:1623)
	java.awt.Window.setVisible(Window.java:1014)
	java.awt.Dialog.setVisible(Dialog.java:1005)
	org.sleuthkit.autopsy.report.infrastructure.ReportGenerator.displayProgressPanel(ReportGenerator.java:295)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction.doReportWizard(ReportWizardAction.java:114)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction.actionPerformed(ReportWizardAction.java:177)
	javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	java.awt.Component.processMouseEvent(Component.java:6539)
	javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	java.awt.Component.processEvent(Component.java:6304)
	java.awt.Container.processEvent(Container.java:2239)
	java.awt.Component.dispatchEventImpl(Component.java:4889)
	java.awt.Container.dispatchEventImpl(Container.java:2297)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	java.awt.Container.dispatchEventImpl(Container.java:2283)
	java.awt.Window.dispatchEventImpl(Window.java:2746)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	java.awt.EventQueue.access$500(EventQueue.java:97)
	java.awt.EventQueue$3.run(EventQueue.java:709)
	java.awt.EventQueue$3.run(EventQueue.java:703)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	java.awt.EventQueue$4.run(EventQueue.java:733)
	java.awt.EventQueue$4.run(EventQueue.java:731)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	java.util.concurrent.FutureTask.report(FutureTask.java:122)
	java.util.concurrent.FutureTask.get(FutureTask.java:192)
	javax.swing.SwingWorker.get(SwingWorker.java:602)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction$ReportWorker.done(ReportWizardAction.java:251)
	javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	javax.swing.Timer.fireActionPerformed(Timer.java:313)
	javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	java.awt.EventQueue.access$500(EventQueue.java:97)
	java.awt.EventQueue$3.run(EventQueue.java:709)
	java.awt.EventQueue$3.run(EventQueue.java:703)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	java.security.AccessController.doPrivileged(Native Method)
	java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	java.awt.Dialog.show(Dialog.java:1084)
	java.awt.Component.show(Component.java:1671)
	java.awt.Component.setVisible(Component.java:1623)
	java.awt.Window.setVisible(Window.java:1014)
	java.awt.Dialog.setVisible(Dialog.java:1005)
	org.sleuthkit.autopsy.report.infrastructure.ReportGenerator.displayProgressPanel(ReportGenerator.java:295)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction.doReportWizard(ReportWizardAction.java:114)
	org.sleuthkit.autopsy.report.infrastructure.ReportWizardAction.actionPerformed(ReportWizardAction.java:177)
	javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	java.awt.Component.processMouseEvent(Component.java:6539)
	javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	java.awt.Component.processEvent(Component.java:6304)
	java.awt.Container.processEvent(Container.java:2239)
	java.awt.Component.dispatchEventImpl(Component.java:4889)
	java.awt.Container.dispatchEventImpl(Container.java:2297)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	java.awt.Container.dispatchEventImpl(Container.java:2283)
	java.awt.Window.dispatchEventImpl(Window.java:2746)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	java.awt.EventQueue.access$500(EventQueue.java:97)
	java.awt.EventQueue$3.run(EventQueue.java:709)
	java.awt.EventQueue$3.run(EventQueue.java:703)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	java.awt.EventQueue$4.run(EventQueue.java:733)
	java.awt.EventQueue$4.run(EventQueue.java:731)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by rodhalverson** [comment]
can I download the beta? or is there a patch I can try?

**Comment by markmckinnon** [comment]
`This has been fixed in the new release of Autopsy (4.20.0).  Closing this out as complete, if it is still an issue you can reopen the issue.
