### ISSUE TITLE
python example modules

### ISSUE THREAD

**Issue by dyussekeyev** [sleuthkit/autopsy#7641]
Hi, everyone.

I am doing my first steps in python modules development and tried to run fileIngestModule.py example on sample disk image. However, I did not receive any results. Is it normal behavior of the module?

Could you please confirm that examples from the Github work fine for the latest version of autopsy?

Askar.

**Comment by markmckinnon** [comment]
The fileingestmodule.py does produce an error in version 4.19.3.  If you look at the following line 137

            art = file.newAnalysisResult(BlackboardArtifact.Type.TSK_INTERESTING_ITEM, Score.SCORE_LIKELY_NOTABLE,
                                         None, "Text Files", None, attrs).getAnalysisResult()

The error is in the BlackboardArtifact.Type.TSK_INTERESTING_ITEM which it cannot find.  You can change it to BlackboardArtifact.Type.TSK_INTERESTING_FILE_HIT and it will then work.  I will submit a PR for this shortly.  If there are any questions let me know.

Kind regards.

Mark

**Comment by markmckinnon** [comment]
The PR to fix this is https://github.com/sleuthkit/autopsy/pull/7642.

**Comment by dyussekeyev** [comment]
@markmckinnon thank you!
