### ISSUE TITLE
Not support Java Adoptium

### ISSUE THREAD

**Issue by girl313** [sleuthkit/autopsy#7747]
Hi,

I use: https://adoptium.net/
(OpenJDK17U-jdk_x64_windows_hotspot_17.0.6_10)

i get a message that java was not found: https://i.imgur.com/ykNQpPm.png

I have tried setting various environment variables but with no success.

Other standarts variables normal works: https://i.imgur.com/HfGzzL1.png

**Comment by markmckinnon** [comment]
Java 17 is not supported until the next release of Autopsy.  Any release after Autopsy 4.20.0 will support Java 17
