### ISSUE TITLE
Time information missing for Logical files import 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by swiss-JF** [sleuthkit/autopsy#7830]
I am running Autopsy 4.20.0 on a Windows 11 Enterprise Evaluation Virtual Machine running in Oracle VM Virtualbox Manager. I have a set of files. I installed the tool after having downloaded it from here: https://sleuthkit.org/support.php and I followed the standard installation procedure. I created a case. The source type is from "logical files". All ingest modules are selected. I let it run and then when I view the files  view the "Modified Time", the "Change Time", the "Access Time", and the "Created Time" shown are 0000-00-00 00:00:00.

However, in the Timeline Editor some dates appear in connection with Event.

If I look at these files' properties in Windows explorer I can see the different information about the date.

Not sure what could be the issue.

![image](https://github.com/sleuthkit/autopsy/assets/63421039/62fa413e-af1d-489d-aa20-a4206013fe28)

**Comment by markmckinnon** [comment]
Logical files in 4.20.0 will not show any timestamp attributes.  In 4.21.0 this has been changed to allow the timestamps to be added with the files.  Note that there is no guarantee that the timestamps are accurate as they can be changed via the OS.  You will have to readd the data source to your case to see this.  If there are any issues please open a new issue or reopen this one.
