### ISSUE TITLE
Failure in recognizing EXT3 filesystem from The Honeynet Compromised Server challenge

### ISSUE THREAD

**Issue by malthousiast** [sleuthkit/autopsy#7925]
When opening the /dev/sda1 disk image from the honeynet compromised challenge ([link](https://cyberdefenders.org/blueteam-ctf-challenges/ulysses/)), Autopsy v4.21.0 on Windows and Linux fails recognizing the partition filesystem.

Repro:
- install Autopsy 4.21.0 (Win x64 or Linux)
- start autopsy, create a new case and add a data source
- Select Disk Image or VM File
- Next, untick all Ingest modules

Result:
"Errors occurred while ingesting image 
1. Cannot determine file system type (Sector offset: 0) "

**Comment by simsong** [comment]
@malthousiast  - why did you close this ticket?
