### ISSUE TITLE
Request: Override export folder

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#838]
When working with Autopsy earlier, I've experienced that placing the case folder on a network share gives slower response times in the GUI. However, when working on a case, I often use multiple tools, and want to export data from these to the same location, which is a predefined location on a network share and not in Autopsy's case structure.

The current export folder location for a case is fine as a default, but it'd be great if this folder could be overridden by the user so that further exports are placed in this user defined folder.

**Comment by bcarrier** [comment]
This is in the 4.9.0 release.
