### ISSUE TITLE
Autopsy 3.1.0: "Tools" menu has no options

### ISSUE THREAD

**Issue by dkarpo** [sleuthkit/autopsy#863]
On a fresh install of Autopsy 3.1.0, on a machine which previously had Autopsy 3.1.0 beta 2 and previous versions installed, the "Tools" menu item only shows pull-down menu items when no case has been created.  Once a case has been created, "Tools" no longer displays any pull-down menus when selected.  Deleting 'C:\Users\<username>\AppData\Roaming\autopsy' corrects the issue.

**Comment by rcordovano** [comment]
This is no longer an issue and Autopsy 4.1.0 will be released shortly.
