### ISSUE TITLE
Can't export files from Mac filesystem

### ISSUE THREAD

**Issue by kefir-** [sleuthkit/autopsy#903]
I have an image from a Mac OS X machine. When looking at the file names in autopsy, they have a :DATA extension appended to the name.

When I try to export these files, the file names are created in the Export folder without the :DATA extension, but all the exported files are 0 bytes in size. I can view the content in Autopsy, but I can't export the content. I've tried exporting full folder structures and single files. The output files (and folders) always seem to be created, but never get any content.

(Incidentally, autopsy doesn't always render pictures. Looking at the headers, they files look fine. It seems like files called .jpg:DATA always render, but for files named .png:DATA, the "Media" tab is greyed out even though the data looks like a PNG file. Don't know if this is related in any way.)

**Comment by bcarrier** [comment]
Fixed and in the last release.

**Comment by kefir-** [comment]
Thanks!
