### ISSUE TITLE
Make deleted files limit a user option

### ISSUE THREAD

**Issue by jletourneau-basistech** [sleuthkit/autopsy#942]
From forum discussion: http://forum.sleuthkit.org/viewtopic.php?f=6&t=92

**Comment by mulder1** [comment]
4 years later.. nobody cares about the 10.000 deleted files limit anymore?

**Comment by bcarrier** [comment]
We care about the general problem of displaying large numbers of items, but haven't focused much on that specific node.   We've been doing a lot of changes to make various views more efficient.  We'll bump the deleted files node up in the list.

**Comment by rcordovano** [comment]
In the Autopsy 4.9.0 release, we made it possible to configure the maximum number of deleted files that can be displayed. In the upcoming 4.10.0 release, this approach is being adopted across the board. There will also be "spot" fixes for the performance of the display of nodes in the results view in the 4.10.0 release. We are looking at more comprehensive solutions such as paging for possible inclusion in the 4.11.0 release.
