### ISSUE TITLE
"Help Contents" main landing page does not change.

### ISSUE THREAD

**Issue by BitSniffing** [sleuthkit/autopsy#953]
Release - 3.1.0

Navigation - Help -> Help Contents

Steps To Repeat - Click on "Quick Start Guide", content will pull up.  Then click on "Overview", content will pull up.  Then click on any of the other main sections and no content appear.

The first two major sections, "Quick Start Guide" and "Overview" show information according to its page.  When navigating to other major sections, such as "Ingest", "Result Viewers", and all others, no introductory information appears about that subject.  What remains in view is the last page sub-section that was reviewed.

Regards,

craig

**Comment by bcarrier** [comment]
Javadocs are now entirely removed. Online version mentioned above is where all of the user docs are located.  They are currently being updated.
