### ISSUE TITLE
Reporting:  First choice of module templates to use when producing a report.

### ISSUE THREAD

**Issue by BitSniffing** [sleuthkit/autopsy#974]
Release:  3.1.0

Details:  After pressing "Generate Report", the next screen asks "Select and Configure Report Modules" and five choices are given with "Results - Excel" being the first.  I am presuming that "Results - HTML" would be the usual choice that an investigator would use, and if so, could "Results - HTML" be allowed to be the first choice over Excel?

**Comment by bcarrier** [comment]
Checked in via #1101
