### ISSUE TITLE
Jython module import

### ISSUE THREAD

**Issue by skusa108** [sleuthkit/autopsy#988]
In the jython.jar included with Autopsy 3.1.1 (Jython version 2.5.3), there are issues with importing certain built-in Jython modules.  Attempting "import os" in an Autopsy report module results in the error "ImportError: No module named os".  Importing "re" results in the same error.  Both are built-in libraries that should be included with Jython.

Replacing c:\Program Files\Autopsy-3.1.1\autopsy\modules\ext\jython.jar with the jython-standalone-2.5.4-rc1.jar (renamed to jython.jar) from jython.org solves the problem and does not seem to introduce any issues into the Autopsy environment.

**Comment by rcordovano** [comment]
Autopsy was using the wrong Jython JAR file, sans many built-in Python libraries, as noted. This has been fixed. The latest code can be obtained from github via the develop branch (bleeding edge), or the workaround described by skusa108 can be used util the next Autopsy release.

**Comment by skusa108** [comment]
Fantastic, thanks for the fix Richard!

-Sam

On Wed, May 6, 2015 at 10:13 AM, Richard Cordovano <notifications@github.com
